### ISSUE TITLE
Detail page - Long profile names break layout

### ISSUE THREAD

**Issue by tbrlpld** [MozillaFoundation/foundation.mozilla.org#10093]
## Description

When a name gets very long, it breaks the layout in on the research detail page author listing component. 

![Screenshot 2023-02-02 at 08.40.24.png](https://images.zenhubusercontent.com/61e1e4f0d1fded7471402d12/62971a27-49d7-4462-99a0-021e596b384a)

It almost happens here (but not quite): https://foundation.mofostaging.net/en/research/library/research-to-shift-power-through-data-governance-example/

To solve this, Design has asked us to update the styling so the name gets broken with a hyphen.

## Acceptance criteria

- [ ] Given a very long profile name, when I see it in the "project leads" section of a Research Hub detail page, the name is broken over multiple lines with hyphens.

**Comment by tbrlpld** [comment]
cc @beccaklam

**Comment by mtdenton** [comment]
Had a discussion on ENG, would like to discuss with DES on the various ways we could go about fixing this with pros and cons for the methods. Example methods:

Character limit
Decreasing font size
Layout shift based on character count

**Comment by tbrlpld** [comment]
Related reading: https://css-tricks.com/snippets/css/prevent-long-urls-from-breaking-out-of-container/

**Comment by tbrlpld** [comment]
Also related: https://justmarkup.com/articles/2015-07-31-dealing-with-long-words-in-css/

**Comment by mtdenton** [comment]
@kristinashu thoughts here on how we should approach this issue? Seems like breaking with a hyphen is the clearest, easiest fix.

**Comment by danielfmiranda** [comment]
Hi everyone! @mtdenton @kristinashu 

After some further research, I believe I have found the reason for the "`hyphens:auto` CSS rule not working on FF/Chrome" problem.

I have found this [issue in the w3c repo](https://github.com/w3c/csswg-drafts/issues/3927) in which there is a large discussion about whether or not words that start with a capital letter should be hyphenated.

The decision that was made from the discussion was that in some languages, in our case English, words that start with capital letters are "Proper Nouns" and should **not** be hyphenated.

Since we are in fact rendering proper nouns (names of the authors), these words will not hyphenate even if they are overflowing out of their containing div.

Related W3C PR: [Avoid auto-hyphenating capitalized words, except for German](https://github.com/mjfroman/moz-libwebrtc-third-party/commit/eae83c6d02d0b022d3007a78aea75e1612b8bf18)

---


### I see two possible solutions to this:

**Option 1 (slight hack but will give us desired results):**
We can update **only** the div housing the profile name with `lang_code="de"`so it can use German hyphenation rules, and hyphenate long names if needed.

**Note**: I am not sure if this will have any negative implications regarding accessibility.

<img width="350" src="https://github.com/MozillaFoundation/foundation.mozilla.org/assets/18314510/323da85f-aa3c-4184-a46a-3d1248027daf">

**Option 2:**

We ask design if there is any other way they would like to handle extra long last names. For example breaking the word works as expected, the only catch is that there is no hyphen.

<img width="350" src="https://github.com/MozillaFoundation/foundation.mozilla.org/assets/18314510/de5022c2-9075-4763-8f7a-d17208071506">

**Comment by mtdenton** [comment]
Nice find @danielfmiranda. I'm going to suggest that we don't reinvent the wheel (or throw in any hacks) and go with the recommendation to break to a new line without a hyphen. We've already spent way too much time on this for the value that it brings IMO.

**Comment by kristinashu** [comment]
Interesting, thank you for looking into this Daniel! Agree, breaking it on to a new line without a hyphen sounds good.

**Comment by danielfmiranda** [comment]
Thanks both! I have submitted a PR and am going to remove the needs discussion label.

**Comment by danielfmiranda** [comment]
Hi @kristinashu! 

This ticket has been merged into staging and is now ready for QA at: https://foundation.mofostaging.net/en/research/library/the-lost-art-of-mathematical-modelling/

I have created a new user with a long last name. I was wondering if you could please take a look at the test page I linked above whenever you are free, and let me know if the name is wrapping as expected? 

Thanks in advance!

**Comment by kristinashu** [comment]
Looks good, thank you Daniel!

**Comment by kristinashu** [comment]
It turns out this isn't working as expected. My assumption is that it would continue to line break when there are spaces and then wrap only if a word/name is too long to fit on a single line. But it looks like this is not line breaking at spaces and only wrapping. 

E.g.

Instead of "Augustin Chaintre / au"  I would expect this to be "Augustin / Chaintreau" since Chaintreau would fit on the second line. And if it was Augustin  Chaintreauuuuuuuuuuuu then it would be something like "Augustin / Chaintreauuuuuuu / uuuuu"

If it isn't straightforward to have it line break at spaces and only wrap if a word doesn't fit then perhaps we should revert to breaking at spaces. 

Screen caps from prod:

![image](https://github.com/MozillaFoundation/foundation.mozilla.org/assets/1068783/5f20ea79-7ba9-4952-b6d5-fdfc36c489c9)

![image](https://github.com/MozillaFoundation/foundation.mozilla.org/assets/1068783/47c0d15b-7eaa-47e3-88c1-dbf3b26df740)

cc @beccaklam @jhonatan-lopes

**Comment by jhonatan-lopes** [comment]
Thanks @kristinashu! It seems that what we want might be the [`hyphenate-limit-chars` CSS property](https://developer.mozilla.org/en-US/docs/Web/CSS/hyphenate-limit-chars). However, that is not available on Firefox or Safari yet (it seems to be a Chromium feature for now).

In the meantime we can revert the changes made and just break on spaces.

**Comment by danielfmiranda** [comment]
Hi @kristinashu! This has been merged into main and is now ready for QA testing on staging.

Can you please take a look at a research article whenever you have a free moment, and confirm if the research author names are now breaking on spaces as expected?

Thanks!

**Comment by kristinashu** [comment]
Yes, looks good for both the research and rcc playbook. Thank you!
