### ISSUE TITLE
[PNI] Feature a campaign/petition on PNI homepage

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/foundation.mozilla.org#10149]
Currently, the PNI homepage can only feature Buyers Guide Article Pages but I would also like to be able to feature a Buyers Guide Campaign Page.

Screen cap of homepage feature section
<img width="1237" alt="image" src="https://user-images.githubusercontent.com/1068783/218533074-dda65ac6-3da6-4d2a-bfc2-bc25a114ff18.png">

#### Screen caps of process
I've created a petition page
<img width="1417" alt="image" src="https://user-images.githubusercontent.com/1068783/218532623-9e865f56-688a-443b-9a2a-cadf4e6c70cb.png">

I would like to feature it on the PNI homepage
<img width="1425" alt="image" src="https://user-images.githubusercontent.com/1068783/218532848-8e3b5314-dc96-490f-9006-80af89c77779.png">

But the Campaign pages don't show up as an option in the page picker
<img width="1417" alt="image" src="https://user-images.githubusercontent.com/1068783/218532668-236f6b5c-18e1-40a8-9142-6c7493c63c33.png">

## AC
- [x] As an editor, I can add the Buyers Guide Campaign Page type as a Main or Supporting Article feature (the same way I would add an Article)
- [x] As a visitor, I can see a petition page as featured at the top of the PNI homepage the same way I would see an Article 

cc @tbrlpld @cdanfon @mtdenton

**Comment by kristinashu** [comment]
@mtdenton can this make it into this sprint since the pni petition will launch soon and I believe it is a small update?

**Comment by danielfmiranda** [comment]
Hi @kristinashu! I have one quick question regarding the wording used in the CMS.

Since now we are able to choose from both Article Pages and Campaign Pages, I was wondering if I should update the wording in the CMS from "Articles" to "Pages", it would look like this:

![Screenshot 2023-02-23 at 16-27-23 Wagtail - Editing Buyers Guide Page Privacy not included](https://user-images.githubusercontent.com/18314510/221062185-b2d279a6-6484-4f3c-a6b9-86afdccde9d9.png)


thanks!

**Comment by kristinashu** [comment]
Nice catch! Yes, page works for me. Thank you!

**Comment by cdanfon** [comment]
This ticket was originally estimated as a 2, but after having implemented the solution this looks more like an 8.

**Comment by danielfmiranda** [comment]
Hi Claudia! Going to update this to a 4 to reflect the time this ticket has taken me. The solution is not too complex, was just a little time consuming to implement. Thanks!

**Comment by danielfmiranda** [comment]
Hi @cdanfon thanks for the update!

For transparency: The solution to this ticket is not too complex. But since the changes are backwards-incompatible ([docs about field changes/renames)](https://github.com/MozillaFoundation/foundation.mozilla.org/blob/main/docs/workflow.md#rename-or-change-a-field-type), the PR process may take a little longer than usual as it has to be split into 3.

**Comment by danielfmiranda** [comment]
Hi @kristinashu! 

This update is now on staging and ready for QA. Can you please take a look whenever you find a free moment? 

Thanks!

**Comment by kristinashu** [comment]
It's working well, thank you Daniel!
