### ISSUE TITLE
Images in Content block are low quality on article pages

### ISSUE THREAD

**Issue by nancyt1** [MozillaFoundation/foundation.mozilla.org#10236]
Compared to using the Image block (bottom), adding images via the Content block renders in lower quality no matter the size.

Screenshot:
![](https://user-images.githubusercontent.com/74557207/222017097-33d8f585-a6cc-4fbe-9a8f-101e3f33e770.png)

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/TP1-134)

**Comment by danielfmiranda** [comment]
Hi @nancyt1!

After diving into this issue, I realized we’ve run into this problem before ([previous issue](https://github.com/MozillaFoundation/foundation.mozilla.org/issues/6068)). The blurriness you're seeing seems to be due to Wagtail’s default resizing behavior within content/rich text blocks.

Unfortunately, Wagtail limits our control over how these images are rendered. However, to address this, we introduced a "full width high quality" option as a workaround, which you can see in [this PR](https://github.com/MozillaFoundation/foundation.mozilla.org/pull/6087). 

<img width="252" alt="image" src="https://user-images.githubusercontent.com/2492510/106198688-35fa7980-6169-11eb-87fa-885a93c14661.png">


Could you check if this resolves the issue? If so, feel free to close the ticket.

Thanks in advance 🙌

**Comment by nancyt1** [comment]
@danielfmiranda The block on the [article](https://foundation.mozilla.org/cms/pages/22313/edit/) page templates don't have that option. Should we do something else in this case? 

<img width="915" alt="Screenshot 2024-09-11 at 4 03 00 PM" src="https://github.com/user-attachments/assets/28269969-9ffd-474c-bbee-42780f9102ae">

**Comment by danielfmiranda** [comment]
Hi @nancyt1,

Thanks for the screenshot! It appears that you're working with the standalone "Image" block, which renders in high quality because we have more control over how the image is handled in the template.

![Screenshot 2024-09-12 at 18-10-41 Editing Article page AI Transparency in Practice - Wagtail](https://github.com/user-attachments/assets/603ad9fc-f345-4334-a2f1-de1801dcf796)


However, the issue mentioned in the ticket relates to images added through the "Content" block.

These images, since they are part of the content block's data, do not give us as much control in the way they image is rendered, resulting in the low-quality rendering issue. 

The "full width high quality" option mentioned earlier is a workaround for this limitation.

<img width="500" alt="Screenshot 2024-09-12 at 6 16 37 PM" src="https://github.com/user-attachments/assets/411d7cac-ac5e-4150-9b39-133b4a1c0b12">
<img width="500" alt="Screenshot 2024-09-12 at 6 15 53 PM" src="https://github.com/user-attachments/assets/0bc6bca0-45fb-44ab-baaa-cb926b67a770">
<img width="500" alt="Screenshot 2024-09-12 at 6 15 53 PM" src="https://github.com/user-attachments/assets/d0172f75-5425-43a3-b8d0-c51e1b7fb262">
<img width="500" alt="Screenshot 2024-09-12 at 6 15 53 PM" src="https://github.com/user-attachments/assets/e2106c6d-5d06-428d-b9f7-32d552f049cf">



When you have a moment, could you please try adding an image following the steps above and let me know if the low-quality rendering issue persists?

Thanks!
