### ISSUE TITLE
[FA] Form Design

### ISSUE THREAD

**Issue by mmmavis** [MozillaFoundation/foundation.mozilla.org#10469]
From the [SPIKE ticket](https://github.com/MozillaFoundation/foundation.mozilla.org/issues/10468), we have decided to go with the HTML embed option. This means we will be able to style UI like form labels, input boxes, and submit button to the design we want. However, we have no controls over the validation bits (including design) as they are being handled by FormAssembly's script.

**Comment by mtdenton** [comment]
I'm heavily recommending "Embed HTML".

- FA hosted form won't go into the page.
- Iframe would restrict analytics measurement and styling and JS event detection will be far more difficult
- Server-side pulling will restrict our ability to use Wagtail localization since the form is pulled directly from FA on user request. If the form ever changes on the FormAssembly side, it will cause big problems in either the Embedded or API situation for us.

We need to stress the importance that this form should never change on the FA side unless there's a concerted effort between CRM and Web Platforms to replace the existing form (in which case I'd recommend creating a brand new form instead). Doing so would break this form in production.

**Comment by mmmavis** [comment]
@kristinashu To my understanding we want to style the new form to be as close as what we have currently. Other than giving up how we do form validation, I would like to inform the design team that we won't be able to keep the fancy effect where clicking on a petition input field shrinks and repositions the input label (e.g., First name) to top left corner of the field. This is because to achieve this, we'll need to alter how the HTML embed code is structured and add in more custom JS code, both create the possibilities of breaking FormAssembly's form script. I've started implementation yet. Could you let me know which designer I should work with if I need design input for FormAssembly work?

**Comment by kristinashu** [comment]
Hi @mmmavis, it makes sense that we can't do the fancy animation. When do you anticipate the need for design support? @nancyt1 or I could help!

**Comment by mmmavis** [comment]
I will set up a review app today to get design input.

**Comment by mmmavis** [comment]
Nancy and I worked on this earlier this week. PR has been merged into the the FormAssembly feature branch. I think we are good to close this ticket. Thanks all!
