### ISSUE TITLE
[SPIKE] Investigate needed tests for newsletter signup

### ISSUE THREAD

**Issue by mmmavis** [MozillaFoundation/foundation.mozilla.org#10540]
We should set up tests or error reporting to ensure posting to Basket doesn't fail without us noticing.

Timebox to 4 hours.

## Dev Task
* Decide what scenarios should trigger Sentry reporting
* Add code to enable the reporting & configure Sentry (if needed)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/TP1-152)

**Comment by mmmavis** [comment]
Hey @tbrlpld 👋🏻 , I've recently added Playwright tests for the newsletter submission flow so we have front-end test coverage there. I think the problem lies more on our currently newsletter form lacking error handling (ticket filed #11406). Basically if anything goes wrong in the POST call, users won't know because we don't do anything about it nor show feedback to users.

> Would these test be to for an outage of basket? Or our basket related code failing in some case?

Both if possible, but I'm not sure if CI will be a good place for testing Basket outage. Any suggestions?

**Comment by tbrlpld** [comment]
> Hey @tbrlpld 👋🏻 , I've recently added Playwright tests for the newsletter submission flow so we have front-end test coverage there. I think the problem lies more on our currently newsletter form lacking error handling (ticket filed #11406). Basically if anything goes wrong in the POST call, users won't know because we don't do anything about it nor show feedback to users.
> 
> > Would these test be to for an outage of basket? Or our basket related code failing in some case?
> 
> Both if possible, but I'm not sure if CI will be a good place for testing Basket outage. Any suggestions?
> 
> Relevant links:
> 
> * [networkapi/campaign/views.py](https://github.com/MozillaFoundation/foundation.mozilla.org/blob/main/network-api/networkapi/campaign/views.py)
> * [Playwright tests](https://github.com/MozillaFoundation/foundation.mozilla.org/blob/main/tests/integration/newsletter/001-blog-body.spec.js)

Hi @mmmavis. Thanks for this added context. That makes sense. In this case, our efforts may be better invested in adding the error handling for the forms #11406, and add tests while adding that. The form should be something we can test without hitting the real Basket API and isolate the handling on our end and make sure we report an error to the user for retry (or similar). 

As for the Basket outage: I agree, testing is probably not the right place. This might be better handled through uptime monitoring and error reporting. I believe Sentry is set up. We might need to look into how Sentry reports errors (who gets notified and how).

**Comment by data-sync-user** [comment]
➤ Simon Acosta Torres commented:

Tyler Denton Currently this is a P1, but not something that we have plans on doing (unless we do want to add). So maybe not removing ticket, but update the priority would be good here.

**Comment by data-sync-user** [comment]
➤ Mavis Ou commented:

Instead of adding more tests, we should improve error monitoring coverage for this. 

One improvement we should do to help our Sentry setup in the codebase in general is to load and initialize the Sentry browser script in the <head> section, rather than including it in main.compiled.js (see here ( https://github.com/MozillaFoundation/foundation.mozilla.org/blob/main/source/js/main.js#L77-L81 )), as it currently loads near the end of the <body> (see here ( https://github.com/MozillaFoundation/foundation.mozilla.org/blob/main/network-api/networkapi/templates/pages/base.html#L154 )). This ensures that Sentry is initialized before any other scripts on the page, so that it can capture errors from the very start.

By default, Sentry should already be capturing errors like

  * uncaught exceptions:  ReferenceError, TypeError, SyntaxError etc
  * resource load failures
  * and more

We should discuss as a team to decide what other errors / actions we want to monitor and how we want to label/categorize them on Sentry dashboard.

**Comment by data-sync-user** [comment]
➤ Simon Acosta Torres commented:

Hey Mavis Ou , the new_site_considerations label should be enough. Once the code freeze is in effect, I will make sure that every ticket that is labelled that way is tracked in the roadmap so we can reference this work later on the process for the new site. Thank you!
