### ISSUE TITLE
[CMS Clean Up] Streamline Image Blocks

### ISSUE THREAD

**Issue by beccaklam** [MozillaFoundation/foundation.mozilla.org#10667]
_From the Streamfield Blocks Audit work (#10607):_

Explore whether it would be possible to merge 'Annotated Image Block', 'Article Image Block', 'Image Block', 'Article Full Width Image Block' and potentially 'Article Double Image Block'?

* [x] Review blocks
* [x] Design first draft of merged block
* [x] Share with design & dev teams and potential key stakeholders the block could affect
* [ ] Make any necessary changes
* [ ] Share final design for feedback
* [ ] Create design to dev ticket

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/TP1-155)

**Comment by dlopezvsr** [comment]
The first draft of the proposed merge between the blocks previously mentioned its finished and ready for reviews and adjustments. It is important to mention that this change will have impact on the current data model structure at the moment of migrations, due to the upgrade to a more complex data model, from blocks.StructBlock to a blocks.StreamBlock.

[Link to commit of new Block merged](https://github.com/MozillaFoundation/foundation.mozilla.org/compare/main...feature/TP1-155-cleanup-streamline-image-blocks)

- [Annotated Image Block](https://github.com/MozillaFoundation/foundation.mozilla.org/blob/719493c30c1941eb0e864a38e970df34318cbdf4/network-api/networkapi/wagtailpages/pagemodels/customblocks/annotated_image_block.py#L14) 
- [Article Image Block](https://github.com/MozillaFoundation/foundation.mozilla.org/blob/4a398f6d9c6cd321e0b31a5e77429afffb6e50b6/network-api/networkapi/wagtailpages/pagemodels/customblocks/articles.py#L53)
- [Article Full Width Image Block](https://github.com/MozillaFoundation/foundation.mozilla.org/blob/4a398f6d9c6cd321e0b31a5e77429afffb6e50b6/network-api/networkapi/wagtailpages/pagemodels/customblocks/articles.py#L33)
- [Article Double Image Block](https://github.com/MozillaFoundation/foundation.mozilla.org/blob/4a398f6d9c6cd321e0b31a5e77429afffb6e50b6/network-api/networkapi/wagtailpages/pagemodels/customblocks/articles.py#L14)
- [Image Block](https://github.com/MozillaFoundation/foundation.mozilla.org/blob/c9853c1dc98e0b3daf6a032499654e078f23a43c/network-api/networkapi/wagtailpages/pagemodels/customblocks/image_block.py#L5)

Once feedback is provided we can proceed with changes and creation of dev ticket.

@robdivincenzo @ramram-mf would be amazing if you can rewiew when got any chance. Thank you!

FYI @simont-cr

**Comment by dlopezvsr** [comment]
Hi @danielfmiranda and @robdivincenzo,

This is one of the issues we reviewed earlier on the call with Rebecca. It would be great if you can take a look to this first draft of the blocks merged, and share your ideas, suggestions, or any comments. I just created also a draft of [PR](https://github.com/MozillaFoundation/foundation.mozilla.org/pull/12745), in case you want to take also a look in there. 

Thank you so much for considering this. 🙌 

> The first draft of the proposed merge between the blocks previously mentioned its finished and ready for reviews and adjustments. It is important to mention that this change will have impact on the current data model structure at the moment of migrations, due to the upgrade to a more complex data model, from blocks.StructBlock to a blocks.StreamBlock.
> 
> [Link to commit of new Block merged](https://github.com/MozillaFoundation/foundation.mozilla.org/compare/main...feature/TP1-155-cleanup-streamline-image-blocks)
> 
>     * [Annotated Image Block](https://github.com/MozillaFoundation/foundation.mozilla.org/blob/719493c30c1941eb0e864a38e970df34318cbdf4/network-api/networkapi/wagtailpages/pagemodels/customblocks/annotated_image_block.py#L14)
> 
>     * [Article Image Block](https://github.com/MozillaFoundation/foundation.mozilla.org/blob/4a398f6d9c6cd321e0b31a5e77429afffb6e50b6/network-api/networkapi/wagtailpages/pagemodels/customblocks/articles.py#L53)
> 
>     * [Article Full Width Image Block](https://github.com/MozillaFoundation/foundation.mozilla.org/blob/4a398f6d9c6cd321e0b31a5e77429afffb6e50b6/network-api/networkapi/wagtailpages/pagemodels/customblocks/articles.py#L33)
> 
>     * [Article Double Image Block](https://github.com/MozillaFoundation/foundation.mozilla.org/blob/4a398f6d9c6cd321e0b31a5e77429afffb6e50b6/network-api/networkapi/wagtailpages/pagemodels/customblocks/articles.py#L14)
> 
>     * [Image Block](https://github.com/MozillaFoundation/foundation.mozilla.org/blob/c9853c1dc98e0b3daf6a032499654e078f23a43c/network-api/networkapi/wagtailpages/pagemodels/customblocks/image_block.py#L5)
> 
> 
> Once feedback is provided we can proceed with changes and creation of dev ticket.
> 
> @robdivincenzo @ramram-mf would be amazing if you can rewiew when got any chance. Thank you!
> 
> FYI @simont-cr
