### ISSUE TITLE
CMS Clean Up Post-MVP Backlog

### ISSUE THREAD

**Issue by beccaklam** [MozillaFoundation/foundation.mozilla.org#10782]
Body of tickets that came out of the first phase CMS Clean Up Work audits and investigation.

## Page Types
* #10673
* #10674
* #10675
* #10676
* #10707

## Streamfield Blocks
* #10667
* #10668
* #10669
* #10670
* #10671
* #10672

## Documentation
* #10800

┆Issue is synchronized with this [Jira Epic](https://mozilla-hub.atlassian.net/browse/TP1-166)

**Comment by data-sync-user** [comment]
➤ Rebecca Lam commented:

Genevieve Baldassano Since this audit was completed a year ago, some of the information may be outdated. For instance I’ve noticed that there have been new blocks made for the MozFest site (and perhaps some blocks I previously mentioned no longer exist?) I should probably spend some time next sprint going through each ticket to make sure the information is still accurate. After speaking with the developers though, I think streamlining block duplication (at a code/function level) is still relevant, especially as we prepare to give the website a UI refresh. cc: Sabrina Ng Nancy Tran

**Comment by data-sync-user** [comment]
➤ Kevin Duong commented:

Task blocked new designs for development. This may be stale based on new development strategy plans for new site, same instance.

**Comment by data-sync-user** [comment]
➤ Kevin Duong commented:

Simon Acosta Torres please help upgrade on status of the Epic based on new site dev strategy

**Comment by data-sync-user** [comment]
➤ Simon Acosta Torres commented:

Due to the current approach of setting up a new site with new blocks that would follow the approach from the TBX Audit, it makes no sense to fix the old blocks anymore. Therefore, this epic can be properly abandoned.
