### ISSUE TITLE
[MozFest] Footer sign up falls back to Spanish

### ISSUE THREAD

**Issue by TheoChevalier** [MozillaFoundation/foundation.mozilla.org#10891]
Hi,

The newsletter promo header & description in the MozFest website footer appears in Spanish when viewing the page in Kiswahili, Portuguese & Frisian:
https://www.mozillafestival.org/sw/
https://www.mozillafestival.org/pt-BR/
https://www.mozillafestival.org/fy-NL/

<img width="1227" alt="Capture d’écran 2023-07-18 à 16 06 24" src="https://github.com/MozillaFoundation/foundation.mozilla.org/assets/1294206/9dc46224-41d8-4e05-8b55-189466aac781">

The content comes from this snippet https://foundation.mozilla.org/cms/snippets/wagtailpages/signup/edit/25/, currently translated in Dutch, Spanish, French, Frisian & German.

For some reason it falls back to Spanish instead of English for locales that don’t have it translated

**Comment by danielfmiranda** [comment]
Interestingly, I am having trouble reproducing this issue on Staging and on my local machine. Even after running the commands `inv copy-stage-db` or `inv copy-prod-db`, the footer defaults to the English locale as expected.

One thing that I did notice however, was that we are passing the "Mozfest Footer" data to the template by [returning the first Signup snippet with the exact name of "Mozfest".](https://github.com/MozillaFoundation/foundation.mozilla.org/blob/main/network-api/networkapi/mozfest/models.py#L127). 

This may be a shot in the dark, but I am wondering if making this query more specific by also filtering for `locale` could help fix the issue? This would also take care of https://github.com/MozillaFoundation/foundation.mozilla.org/issues/10019, so either way it would be a good update to make.

**Comment by jhonatan-lopes** [comment]
Further investigation shows that @danielfmiranda's hypothesis seems to be right. Running a Django shell locally, we can inquire which `Signup` instance is being taken to be displayed at the footer:

```python
>>> from networkapi.wagtailpages.models import Signup
>>> mozfest_footer = Signup.objects.filter(name__iexact="mozfest").first()
>>> mozfest_footer.locale
<Locale: English>
```

When running the same command on the production site (by running `heroku run "network-api/manage.py shell" -a foundation-mozilla-org`), we get:

```python
>>> from networkapi.wagtailpages.models import Signup
>>> mozfest_footer = Signup.objects.filter(name__iexact="mozfest").first()
>>> mozfest_footer.locale
<Locale: Spanish>
```
Indeed, the issue seems to be with getting the first `Signup` object with `mozfest` name. This should be filtered by the locale. It is a coincidence that the footer falls back to English correctly locally and on staging, as the English version is also the first one on those.
