### ISSUE TITLE
[Blog] - [Blog Page] Replace body definition in factory

### ISSUE THREAD

**Issue by jhonatan-lopes** [MozillaFoundation/foundation.mozilla.org#11129]
The BlogPageFactory uses a [custom definition for its `body` field](https://github.com/MozillaFoundation/foundation.mozilla.org/blob/main/network-api/networkapi/wagtailpages/factory/blog.py#L79), which is not compatible with `wagtail-factories`.

This should be replaced by a `factory.SubFactory` compatible with `wagtail-factories`.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/TP1-193)

**Comment by dlopezvsr** [comment]
Working on this issue and based on the initial information provided, I developed a the following changes ([pull request draft](https://github.com/MozillaFoundation/foundation.mozilla.org/pull/12848)) on the `BlogPageFactory`, where a `StreamFieldFactory` was added next to the implementation of `SubFactory`. However digging deeper due to the failure of `001-default-layout.spec.js` tests, I realized that the premise of this issue regarding the incompatibility of the Faker("streamfield") as a custom field for `wagtail-factories`, is already solved with the implementation of a custom provider `Faker.add_provider(StreamfieldProvider)` ([see code reference](https://github.com/MozillaFoundation/foundation.mozilla.org/blob/782ec60f448697e54c9f6667aa372691ae45f582/network-api/networkapi/mozfest/factory.py#L37)) where all the potential `StructBlocks` for a `StreamField` are defined ([see codebase for reference](https://github.com/MozillaFoundation/foundation.mozilla.org/blob/f1ede5bfd75bae495b9f48a6dc6e4860113ba55e/network-api/networkapi/utility/faker/streamfield_provider.py#L755)).

Considering the information mentioned above, my thoughts are that changing the codebase to Subfactories might increase the complexity of the code unnecessarily. In case the changes mentioned above one year ago (when the issue was created) were not creted yet, we can mark this issue as solved, otherwise it would be great if more context or another point of view can contribute to this conclusion.

FYI @danielfmiranda @simont-cr 
:)

**Comment by data-sync-user** [comment]
➤ Simon Acosta Torres commented:

diego I’m okay with abandoning this issue considering that it’s a legacy issue that has already been resolved in a way and any other fixes would require additional complexity added to the code.

What are your thoughts Daniel Miranda ?

**Comment by data-sync-user** [comment]
➤ Simon Acosta Torres commented:

CC: Rob DiVincenzo

**Comment by data-sync-user** [comment]
➤ Daniel Miranda commented:

Thanks for bringing this to our attention diego ! Given your findings and our current focus on building a new site, I think it's best to set this aside for now since we'll likely need to create new factories for the new site anyway.

**Comment by data-sync-user** [comment]
➤ diego commented:

Daniel Miranda thank you so much for your review, I agree with that!

Simon Acosta Torres we can safely abandon this ticket.
