### ISSUE TITLE
PNI - Articles nav link should be highlighted

### ISSUE THREAD

**Issue by mmmavis** [MozillaFoundation/foundation.mozilla.org#11126]
We have a regression bug where the "Articles" nav link should be highlighted for `/articles` pages but it's not acting like that.

### Example (PNI article page)
https://foundation.mozilla.org/en/privacynotincluded/articles/its-official-cars-are-the-worst-product-category-we-have-ever-reviewed-for-privacy/
<img width="1275" alt="image" src="https://github.com/MozillaFoundation/foundation.mozilla.org/assets/2896608/d5ea1ff6-8ca8-4d7d-bdf2-56f256f93792">

### Expected

<img width="1282" alt="image" src="https://github.com/MozillaFoundation/foundation.mozilla.org/assets/2896608/719e045f-23c3-455a-9fa5-cdaa60c7acc0">

---

## Dev Tasks

- [ ] Make sure the  "Articles" nav link is highlighted for `/articles` on PNI.

## Acceptance Criteria

- [ ] As a site visitor, when I visit a PNI `/articles` page, I can see that the "Articles" nav link is highlighted.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/TP1-192)

**Comment by robdivincenzo** [comment]
At further glance, might be an IA issue to solve here as well. The problem is PNI's "About" primary nav link is actually a child path (/about/why), whereas there's a child link in the sidebar "How to use this guide" that is a parent path (/about/). It's making a simple active state inheritance not work as expected.

I can work around it if necessary, but we might be able to tackle this better if we can change the primary nav route to /about/ instead of /about/why and use /about/how instead of /about/ for the child page. Correcting that should help from an IA and perhaps even SEO perspective.

![primary_nav_click](https://github.com/MozillaFoundation/foundation.mozilla.org/assets/3083419/d7d7f1bd-1644-4fba-ba2c-cc2407432398)
![sidebar_nav_click](https://github.com/MozillaFoundation/foundation.mozilla.org/assets/3083419/281c8b92-2f2c-42ac-bf72-5adaad0a034f)

**Comment by kristinashu** [comment]
Hi @robdivincenzo, your suggestion above sounds good to me as long as /about/ can redirect to /about/how

**Comment by robdivincenzo** [comment]
We are good to simply move the "how" page (/about) into primary nav instead of "why" page (/about/why) per Slack discussion. https://mozilla.slack.com/archives/C04DYP6T6VD/p1710431416217539
