### ISSUE TITLE
Change Donation Modal body text to a`RichTextField`

### ISSUE THREAD

**Issue by mtdenton** [MozillaFoundation/foundation.mozilla.org#11183]
Stakeholder: Michael Whitney
Original request: https://mozilla-hub.atlassian.net/browse/MOFOTP-23

> We would like to be able to add formatting (bold, line breaks, etc.) to the donation modal snippets after you sign petitions, so it’s not just a big block of plain text.

Needs groomed, but seems like we should change `body` from `TextField` to `RichTextField`. We should also put a reasonable character limit here. We should also find out if `header` should remain a `CharField` or convert that as well.

Open questions:
Current data should also be considered. How will the data be migrated? Can we cleanly migrate a text field to a rich text field?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/TP1-195)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/61911">image (7).png</a> | <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/62834">image-20240510-214746.png</a>

**Comment by jhonatan-lopes** [comment]
Current data should also be considered. How will the data be migrated? Can we cleanly migrate a text field to a rich text field?

**Comment by simont-cr** [comment]
@jhonatan-lopes Added this as a P1 as we might want to go back to the stakeholder and let them know if we're either doing this or not. I would say that if the process of migrating is going to be difficult and might cause unintended issues, we might be better off leaving this as it is for the time being. The original deadline for this request was Q1 2024.

**Comment by jhonatan-lopes** [comment]
We can do the data migrations, it just needs to be well thought before proceeding: https://docs.wagtail.org/en/stable/advanced_topics/streamfield_migrations.html#streamfield-migrations

**Comment by simont-cr** [comment]
Let's discuss this in our next sprint planning. Thank you!

**Comment by mmmavis** [comment]
@jhonatan-lopes The field name `body` is probably misleading as we are not talking about the `body` field of a page here 😅  The [donate modal](https://github.com/MozillaFoundation/foundation.mozilla.org/blob/main/network-api/networkapi/wagtailpages/donation_modal.py#L25-L32) is a snippet that has a field called `body` of type `TextField`. I'm assuming changing the field type to `RichTextField` would be simply updating `body = models.TextField(` to `body = models.RichTextField(` and generating the migration file? Is there anything we should worry about for the existing data? For this case it's unlikely that existing data would contain HTML tags in them but I'm still curious generally if we need to run anything to sanitize the data.

**Comment by jhonatan-lopes** [comment]
@mmmavis yep, I'm aware that it is a snippet :grimacing: 

We should definitely start by doing what you said: converting `body = models.TextField` to `body = wagtail_fields.RichTextField` and then creating a migration. The migration that will be created will alter the field to be a `RichTextField`, something like:

```python
    operations = [
        migrations.AlterField(
            model_name="donationmodal",
            name="body",
            field=wagtail.fields.RichTextField(
                default="...",
                help_text="Donation text",
            ),
        ),
    ]
```

What I'm not sure is what comes next. I'm not 100% certain if the `AlterField` migration knows how to convert between a `TextField` and a `RichTextField` automatically so that the data makes sense as a rich text. So, we need to run the migration and verify. If everything looks good with the default migration, then hoooray :tada: we got nothing to worry about.

If not, we will need to figure out how to handle that data so that it is "rich text valid". Does that make sense?

**Comment by mmmavis** [comment]
@jhonatan-lopes Yup! I'll get a copy of prod data to test it locally.

**Comment by mmmavis** [comment]
@jhonatan-lopes Not sure if this is the right way of comparing the before and after values (certainly not the most efficient way I think 😅 ) ...

What I did is to export data in the DonationModal table into json (both before and after the migration), and compare the `body` values of the before/after data to see if any pair doesn't match. In the Python script I used `==` to do the string value comparison. It turned out all "after" body values were identical to their "before" counterpart. I also went into localhost CMS and picked a random donation modal snippet to check its rendering result, which looked the same as what we have on prod. 

Is this the kind of check you had in mind? If not, please let me know how I should proceed. Thanks!

**Comment by jhonatan-lopes** [comment]
If the rendering still works, then that's good enough for me :thumbs-up:

Thanks for checking that

**Comment by mmmavis** [comment]
@kristinashu @mtdenton 

What elements do we wanna allow in the rich text field? I'm thinking just italic, bold, and link. For reference, the section we are talking about here is just the "body" of the donation modal (e.g., `Thank you for signing the petition to call...`)

<img width="1210" alt="image" src="https://github.com/MozillaFoundation/foundation.mozilla.org/assets/2896608/f3348ecd-6cbb-438b-99d1-79f8568c8080">

**Comment by kristinashu** [comment]
@mmmavis I'd recommend you ask Christian since he has a better sense of what the copy would be, I'm not sure what he has in mind.

**Comment by mmmavis** [comment]
Sounds good. Will do!

**Comment by data-sync-user** [comment]
➤ Mavis Ou commented:

Current update:

I reached out to Christian on Slack yesterday. I will update the ticket and file PR once I hear back from him.

**Comment by data-sync-user** [comment]
➤ Mavis Ou commented:

Update:

Christian and team would like to have every feature in the RichTextField ( https://docs.wagtail.org/en/stable/advanced_topics/customisation/page_editing_interface.html#limiting-features-in-a-rich-text-field ) enabled.

!image (7).png|width=1624,height=824,alt="image (7).png"!

**Comment by data-sync-user** [comment]
➤ Mavis Ou commented:

Simon Acosta Torres I just tested this on staging, however, on staging the HTML formatted string doesn’t get rendered as HTML. This is different than what we tested it on the PR stage. I’m gonna dive into it more. If this can’t be fixed before the next deploy then we’ll have to pull out the code changes from main

!image-20240510-214746.png|width=695,height=383,alt="image-20240510-214746.png"!

**Comment by data-sync-user** [comment]
➤ Mavis Ou commented:

Fix is pretty straightforward. Will file a PR now.

**Comment by data-sync-user** [comment]
➤ Simon Acosta Torres commented:

Mavis Ou Thanks for taking a look and even more, for finding a fix for this. This is one of the last few things remaining from stakeholders, so it will be amazing to be able to say its done 🙂

**Comment by data-sync-user** [comment]
➤ Mavis Ou commented:

Fix is under review at the moment: https://github.com/MozillaFoundation/foundation.mozilla.org/pull/12322 ( https://github.com/MozillaFoundation/foundation.mozilla.org/pull/12322|smart-link )

**Comment by data-sync-user** [comment]
➤ Mavis Ou commented:

PR merged and tested on staging. This is ready for prod push!
