### ISSUE TITLE
UTM parameters are not carrying over into FRU from petition pages

### ISSUE THREAD

**Issue by Gbaldassano** [MozillaFoundation/foundation.mozilla.org#11205]
After a supporter signs a petition and is prompted to donate, UTM parameters are not carrying over into Fundraise Up, which means we’re losing data and the ability to do analysis on donations. Thanks in advance for your help! 

Jira ticket: https://mozilla-hub.atlassian.net/servicedesk/customer/portal/20/MOFOTP-28

**Comment by mtdenton** [comment]
Seems like what we need to do is take this:
https://github.com/MozillaFoundation/foundation.mozilla.org/blob/2a8966d48fec33a74dbaf93a9da0663086986594/tests/integration/petition/002-thank-you.spec.js#L8-L9

...and throw any current query parameters to the back of this URL so that they carry over into FRU when the modal is opened. Assigning @mmmavis here since she built this petition work and will have the most context.
