### ISSUE TITLE
[Blog Newsletter] Front-end implementation epic

### ISSUE THREAD

**Issue by jhonatan-lopes** [MozillaFoundation/foundation.mozilla.org#11268]
This epic includes front-end tickets for rendering the new streamfield block `newsletter_signup_block`

**Comment by mmmavis** [comment]
Going to turn this into an epic ticket. Sub-tickets to be added soon.

**Comment by mmmavis** [comment]
Here's my plan for creating a new set of React components, based on atomic design methodalogy, to render this new newsletter signup module (and for all of existing 10+(?) singup box variations in `join.jsx` to eventually migrate to in the future).

In `source/js/`:
```
├── components
│   ├── ...
│   │   └── ...
│   ├── join (existing, all existing signup variations are handled here, won't be touched in this ticket)
│   │   ├── join.jsx
│   │   ├── join.scss
│   │   └── language-select.jsx
│   ├── ...
│   ├── ...
│   ├── ...
│   ├── newsletter-signup (new, to be created)
│   │   ├── atoms
│   │   │   ├── heading.jsx
│   │   │   ├── description.jsx
│   │   │   ├── label.jsx
│   │   │   ├── validation-error.jsx
│   │   │   ├── input-text.jsx
│   │   │   ├── input-checkbox.jsx
│   │   │   ├── select.jsx
│   │   │   ├── button-submit.jsx
│   │   │   ├──
│   │   │   └──
│   │   ├── molecules (e.g., label + input + validation error message)
│   │   │   ├── input-text-field.jsx
│   │   │   ├── input-checkbox-field.jsx
│   │   │   ├── select-field.jsx
│   │   │   ├──
│   │   │   └──
│   │   ├── organisms
│   │   │   ├── blog-page-form.jsx
│   │   │   ├── form-validator.js (HOC)
│   │   │   └──
│   ├── ...

```

I don't love the file structures here as typically directories like `atoms`, `molecules` etc should be moved to higher level. Since this new newsletter box is the first component that we build using atomic design approach, I think it's okay to leave them under `newsletter-signup` dir for now to reduce confusion in codebase.

I'm gonna go ahead and create sub-tickets now.

**Comment by Gbaldassano** [comment]
@mmmavis @jhonatan-lopes FYI I think this ticket needs to be updated to reflect the block/snippet approach we ended up landing on (as opposed to the original plan as building this as part of the page template): Updated PRD is here: [Web Platforms PRD: MVP Blog Newsletter 2.0](https://docs.google.com/document/d/17VA5brmV3LIC4jhFLC_d78EwZ34-S4CKLXi7ZcOFR0M/edit?usp=sharing)

**Comment by mmmavis** [comment]
@Gbaldassano Thanks for the reminder and sorry for the confusion. This ticket is actually a front end work epic ticket. I'll update its title and description to provide more clarities. 

As for details of the block/snippet approach, Tyler has updated [the primary ticket #11265](https://github.com/MozillaFoundation/foundation.mozilla.org/issues/11265) to reflect our new plan :D

**Comment by mmmavis** [comment]
I moved the localization ticket (https://github.com/MozillaFoundation/foundation.mozilla.org/issues/11351) out of this epic because that is now served as an improvement work that can be rolled out later.

**Comment by mmmavis** [comment]
Done!
