### ISSUE TITLE
Optimise `FoundationNavigationPageMixin`

### ISSUE THREAD

**Issue by jhonatan-lopes** [MozillaFoundation/foundation.mozilla.org#11458]
Ensure that the `FoundationNavigationPageMixin` has no N+1 queries.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/TP1-209)

**Comment by data-sync-user** [comment]
➤ Daniel Miranda commented:

After reviewing the FoundationNavigationPageMixin and its associated functionality, I can confirm that the mixin does not suffer from any N+1 query issues.

The primary function, set_main_site_nav_information, retrieves the root homepage and its child pages using get_children().live().in_menu(). This operation is executed in a single query,

Investigating further, the template rendering menu_items only accesses the fields url, title, and full_url. All belong to the base Page model. Since these fields are included in the initial query, no additional database queries are triggered per item within the loop, avoiding any N+1 issues.

As a result, the current implementation is already optimized and no changes are needed.

One point to consider, however, is that since we are now using the new navigation bar populated by a user-curated list, this mixin may no longer be in use. It could be worth investigating whether we should remove it from the codebase or retain it for potential future use.

**Comment by data-sync-user** [comment]
➤ Daniel Miranda commented:

Hi Simon Acosta Torres ! 

After further investigation, I’ve confirmed that this mixin does not experience any N+1 query issues and doesn't require any updates at this time.

However, this investigation has raised a few other questions that I was hoping you could help with:

  * Currently, all pages on the foundation site are using the new, user-curated navigation bar, which can be found here ( https://foundation.mozilla.org/cms/snippets/nav/navmenu/edit/1/ ). That said, I noticed that pages under the “donate” section, such as https://foundation.mozilla.org/en/donate/ ( https://foundation.mozilla.org/en/donate/|smart-link ) , are still utilizing the old navigation bar. Should these be updated to use the new navigation as well? If so, I can create a ticket to capture that work.
  * Additionally, if we do update the donate pages to adopt the new navigation, the FoundationNavigationPageMixin would no longer be in use. In that case, should we remove it from the codebase, or would you prefer we keep it for potential future use?

Thanks!

**Comment by data-sync-user** [comment]
➤ Simon Acosta Torres commented:

While we wait for design on the first question, I would like to continue cleaning up our codebase as much as possible. So if the FoundationNavigationPageMixin would indeed no longer be of use, let’s remove it; we can always restore if we need to in the future if there was another potential use case.

**Comment by data-sync-user** [comment]
➤ Daniel Miranda commented:

Thanks Simon Acosta Torres ! After reaching out to design, they requested that we update donate pages to use the new nav bar. 

I have created https://mozilla-hub.atlassian.net/browse/TP1-1221 ( https://mozilla-hub.atlassian.net/browse/TP1-1221|smart-link )  to capture this work, as well as the removal of the mixin. 

Moving this ticket to closed!
