### ISSUE TITLE
[SPIKE] Evaluate what needs to be moved over to the foundation stack

### ISSUE THREAD

**Issue by mtdenton** [MozillaFoundation/foundation.mozilla.org#11697]
Timebox to 2 hours

**Comment by danielfmiranda** [comment]
After investigating, I have closed the following tickets:

- https://github.com/MozillaFoundation/foundation.mozilla.org/issues/10268
- https://github.com/MozillaFoundation/foundation.mozilla.org/issues/10269
- https://github.com/MozillaFoundation/foundation.mozilla.org/issues/10271
- https://github.com/MozillaFoundation/foundation.mozilla.org/issues/10272
- https://github.com/MozillaFoundation/foundation.mozilla.org/issues/10270
- https://github.com/MozillaFoundation/foundation.mozilla.org/issues/10327
- https://github.com/MozillaFoundation/foundation.mozilla.org/issues/10510


And have created the following tickets:

- https://github.com/MozillaFoundation/foundation.mozilla.org/issues/11737
- https://github.com/MozillaFoundation/foundation.mozilla.org/issues/11736
- https://github.com/MozillaFoundation/foundation.mozilla.org/issues/11738
- https://github.com/MozillaFoundation/foundation.mozilla.org/issues/11739
- https://github.com/MozillaFoundation/foundation.mozilla.org/issues/11740


In order to capture what work is still needed to decommission the donate stack.

Closing this ticket!
