### ISSUE TITLE
What You Can Do cards with clickable titles and images

### ISSUE THREAD

**Issue by simont-cr** [MozillaFoundation/foundation.mozilla.org#11892]
### Describe the bug
From Michael Witney:

> I’d like to make more parts of promotions like on the What You Can Do page be clickable. Right now, the only thing that is clickable is the CTA text at the bottom of the short description. I would like to see the headline and the promo image also made clickable, because they are the most visible and enticing parts of the promotion, but you have to go down to the link to get anywhere.

### To Reproduce
1. Go to https://foundation.mozilla.org/en/
2. Click on What can you do navigation item
3. Scroll down to Ways to Give section
4. Click on the titles or cards, no action triggered

### Expected behavior
User would expect that clicking on either the titles or the images should also trigger the action from the CTA.

### Screenshots
<img width="1133" alt="Monosnap+Mozilla+Foundation+-+What+you+can+do+2024-02-21+13-07-13" src="https://github.com/MozillaFoundation/foundation.mozilla.org/assets/159044329/72aa1408-d1b0-4ff7-b4de-d582ee1e4e3b">
 explain your problem.

### Additional context
Ideal deadline by Q2 2024.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/TP1-82)

**Comment by robdivincenzo** [comment]
Trying to hash out the requirements on if the headline and image should be clickable, and if so what kind of hover states / effects.

Clickable:
Headline
- I think for sure this one should click through
Image?
 - This one I'm not too sure, it's kind of background image-ish. Thoughts?

Hover state:
Headline
- Simple underline and pointer enough?
Image
- Pointer and zoom effect? Any consideration for text or other things getting cropped if zoom effect?

**Comment by kristinashu** [comment]
The blog page is a good example for hover states https://foundation.mozilla.org/blog/ 

<img width="392" alt="image" src="https://github.com/MozillaFoundation/foundation.mozilla.org/assets/1068783/b94fbe96-96ca-42b9-af8e-fff78fae966a">

- The image is clickable but it doesn't have a hover state (just the pointer changes). 

- The headline is underlined and the pointer change. This is consistent with what is in [our Style Guide.](https://www.figma.com/proto/sOxNGYMzwZT0B9Fal2D4WT/%5BWIP%5D-Component-Library?page-id=581%3A5413&type=design&node-id=1946-19618&viewport=1000%2C473%2C0.25&t=1zCmiE1ut6BzlLNi-1&scaling=min-zoom&mode=design) 

I see what your saying that it might be a little odd that the image is clickable on What You Can Do cards because it's in the background. I'm a little torn but since this page is so action orientated (we really want people to click on something), I'm ok with it being clickable.

Agree, the headling should definitely be clickable and will be a big improvement!

**Comment by michaelwhitney13** [comment]
I definitely think the image should be clickable for this, not just the
headline.

**Comment by robdivincenzo** [comment]
Thank you @michaelwhitney13! Both will be clickable next deployment, here is the change hosted on our staging site:

https://foundation.mofostaging.net/en/what-you-can-do/

**Comment by mmmavis** [comment]
This has been fixed. Closing! 🎉
