### ISSUE TITLE
Investigate content.chicagosummeroflearning.org

### ISSUE THREAD

**Issue by danielfmiranda** [MozillaFoundation/foundation.mozilla.org#11923]
The team has reviewed this [list](https://docs.google.com/document/d/17ByHIC_vo_WK7j48x3VauW5LMO_yDK6qvrCE0uQ4IL8/edit) to evaluate AWS resources for potential decommissioning or removal. In the process, we've identified `content.chicagosummeroflearning.org` requires further examination. (Marked with a yellow dot on the google doc)

The purpose of this task is to look into `content.chicagosummeroflearning.org` and confirm whether it can be approved for decommissioning.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/TP1-67)

**Comment by data-sync-user** [comment]
➤ Simon Acosta Torres commented:

Due to the bucket and files themselves created on 2013 and the reference that I can find for this project is here https://wiki.mozilla.org/Badges/chicago ( https://wiki.mozilla.org/Badges/chicago|smart-link ) , we can safely remove considering this is older than 10 years.
