### ISSUE TITLE
Investigate vto.mozillafoundation.org

### ISSUE THREAD

**Issue by danielfmiranda** [MozillaFoundation/foundation.mozilla.org#11933]
The team has reviewed this [list](https://docs.google.com/document/d/17ByHIC_vo_WK7j48x3VauW5LMO_yDK6qvrCE0uQ4IL8/edit) to evaluate AWS resources for potential decommissioning or removal. In the process, we've identified `vto.mozillafoundation.org` requires further examination. (Marked with a yellow dot on the google doc)

The purpose of this task is to look into `vto.mozillafoundation.org` and confirm whether it can be approved for decommissioning.

┆Issue is synchronized with this [Jira Story](https://mozilla-hub.atlassian.net/browse/TP-40)

**Comment by data-sync-user** [comment]
➤ Simon Acosta Torres commented:

Per AWS Audit, Redirects vto.mozillafoundation.org ( http://vto.mozillafoundation.org ) to a Google Form that’s a tool for users to request for VTO. Because this can have its uses outside our current control, is best to keep this bucket open as the other VTO buckets will also stay as they are.
