### ISSUE TITLE
Featured Video Post on the blog index page is linking to English pages

### ISSUE THREAD

**Issue by TheoChevalier** [MozillaFoundation/foundation.mozilla.org#11989]
Hi,

I’ve noticed the "Featured Video Post" on the blog index page is always linking to English pages. It looks like this bloc will need the same treatment as the regular featured blog posts.

Thanks!

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/TP1-50)

**Comment by AdalbertoMoz** [comment]
Hi @TheoChevalier ! Could you please give a look to the [Staging site](https://foundation.mofostaging.net/es/blog/) to confirm that this Issue is fixed?

Note: I don't know if it's correct that the Issue is marked as closed once the PR is merged (automatic behavior of GitHub). Please feel free to re-open it if necessary.

**Comment by TheoChevalier** [comment]
Thanks @AdalbertoMoz, confirming it’s fixed on staging!
