### ISSUE TITLE
SPIKE: Investigate duplicate fires for `form_submission` tag and tracking for newsletters

### ISSUE THREAD

**Issue by nancyt1** [MozillaFoundation/foundation.mozilla.org#12020]
Audrey flagged that we got about 1900+ signups on a [blog post ](https://foundation.mozilla.org/en/blog/is-it-safe-to-shop-on-instagram-tiktok-facebook/)that only had ~800 views. The form_submission tag for newsletter signups is triggered anytime a user clicks "sign up" and this has somehow lead to an average of 3 "signups" per user which creates inaccurate data collection for us. It would be great to update this tag to only triggered on successful signups or open to any other solution. Perhaps we can also removed the hardcoded UA tag? More context in this [slack thread](https://mozilla.slack.com/archives/C04DYP6T6VD/p1709678767305789)

[Spreadsheet](https://docs.google.com/spreadsheets/d/1MDYSJPPwLCpXYxvhNVGVIAiMjwD1waPJW3ZwudtOd4c/edit#gid=0) from Dan comparing GA4 signups and CTMS signups

[Analytics dashboard](https://lookerstudio.google.com/u/0/reporting/90cc15ea-ffd0-4915-9367-6673afd9f80c/page/p_w89zp6drzc)

Timebox: 4 hours

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/TP1-34)

**Comment by mtdenton** [comment]
Changing this to a spike. I'll take a look at this one.

**Comment by data-sync-user** [comment]
➤ Daniel Miranda commented:

Hi Nancy Tran ,

While troubleshooting this issue, I noticed that the "form_submission" event fires every time someone hits the "sign up" button. So, if someone gets a validation error and clicks again, GTM counts each click as a separate submission.

I thought about fixing this by making the event only fire on a successful form submission. But Mavis came up with a different idea—creating a new event called "successful_form_submission" that only triggers after we confirm the submission went through. This way, we can track both the total attempts and the actual successful sign-ups separately.

If we go down this path, I have a follow up question. Right now, there's a GA event called “form submit tap” that fires alongside the GTM event when someone clicks submit:

trackFormSubmit(formData) {
  ReactGA.event({
    category: `signup`,
    action: `form submit tap`,
    label: `Signup submitted from ${
      this.props.formPosition ? this.props.formPosition : document.title
    }`,
  });

  window.dataLayer = window.dataLayer || [];
  window.dataLayer.push({
    event: "form_submission",
    form_type: "newsletter_signup",
    form_location: this.props.formPosition || null,
    country: formData.country,
    language: formData.language,
  });
}Will we need a new GA event too? Or, will updating the GTM event be enough?

I've moved this ticket to the "blocked" column while we figure out our next move.

Thanks!

**Comment by data-sync-user** [comment]
➤ Nancy Tran commented:

Daniel Miranda Hey Daniel! I think it’s a good idea to have a new event for successful form submissions so we can track both. I’m unsure about this GA event but it seems old. Is it hard coded? I think it might be ok to get rid of it if the GTM tag is doing the same thing. I think Mavis would know the history best and if it’s still needed. 

How do you suggest we capture when a form submission is successful? Is there a frontend element to attach a trigger to or would something hardcoded be more accurate? I would love Tyler’s advice on this as well.

**Comment by data-sync-user** [comment]
➤ Mavis Ou commented:

If I remember it correctly, it’s not until ~3 years ago we started using GTM. Before that we solely used GA for tracking/analytics purposes. I would say all (if not, most) of the GA events were set up before we had GTM. However, it seems to me that some teams are still utilizing GA data found on GA. Tyler Denton could you provide some insight here? The GA/GTM/GA4 transition happened while I was away and I’m having trouble recalling what we decided to deprecate or switch to. For ref, there are still many GA events ( https://github.com/search?q=repo%3AMozillaFoundation%2Ffoundation.mozilla.org%20reactga&type=code ) set up in codebase.

**Comment by data-sync-user** [comment]
➤ Tyler Denton commented:

GTM implementation happened before I started, GA4 (new analytics property) implementation happened right around my start date. Because of all the team turnover, I’m guessing the ReactGA events going to UA (the old analytics property that’s being decommissioned) were forgotten, I definitely didn’t know about them. For approach, I would list out these ReactGA UA events that Mavis Ou listed and see if there’s an equivalent fire in GTM going to our GA4 account. Torchbox’s setup is fairly comprehensive and robust but there could still be holes. Once we confirm, we could then remove the ReactGA events (and maybe even ReactGA itself?) because when UA is deprecated this will be firing to nothing.

We should also put together some docs here so that this isn’t lost to time like last time.

Also, if stakeholders want one-to-one accurate numbers on newsletter signups, GA is not the best way to get that. Signup numbers from Basket/CTMS are a much better source of truth. The successful form submission improvement from below helps, but honestly the best we can promise here is that someone attempted the submission process and they didn’t have an ad blocker enabled.

Stakeholders will also no longer have access to UA soon because of Google deprecation so that will also cause less confusion.

Let me know if you need guidance here!

**Comment by data-sync-user** [comment]
➤ Adalberto Vazquez Roman commented:

Regarding the spike, here are the steps I propose:

  * First, I'll create a spreadsheet listing all ReactGA events in our codebase and their key details. This will help us understand our current tracking setup.
  * Next, with some help, I'll check if there are corresponding triggers in GTM that send data to our GA4 account. This will help us identify any tracking gaps and make the transition to GA4 smoother.
  * In the end, we should have a detailed document mapping GTM and GA4 events to properly migrate our GA events to GTM.

I have two questions:

  1. I plan to handle the first step on my own since creating the spreadsheet seems straightforward. However, I’ll need assistance with the second step due to my limited knowledge of GA and GTM events. Does this approach sound reasonable to you, and who should I contact for help?
  2. With Universal Analytics (UA) ending on July 1st and its historical data being deleted, it seems like these "forgotten" events might not be a big issue. But should we still take this seriously and inform other teams? What happens if the events simply get lost? Would anyone be affected?

I'm open to any other recommendations or a different roadmap you might have in mind Tyler Denton Daniel Miranda

**Comment by data-sync-user** [comment]
➤ Tyler Denton commented:

Hi Adalberto Vazquez Roman, thanks for the write-up!

These steps sound great. It won’t be evergreen, but we’ll save that spreadsheet for posterity when it’s finished in docs. For the questions:

  1. Understood. Daniel Miranda is likely who you want here. If y’all run into anything crazy, let me know and I’ll help make sense of it. I can also put together a meeting once the spreadsheet is done if it’s easier for y’all, just let me know.
  2. The data from these events currently isn’t used heavily, but there are plans coming to start using it more effectively. For continuity’s sake, let’s plan to set those events up up one-to-one in GTM as best as we can for those forgotten ReactGA events.

**Comment by data-sync-user** [comment]
➤ Adalberto Vazquez Roman commented:

Hey team,

Here you can find the spreadsheet ( https://docs.google.com/spreadsheets/d/1FeUo7XPakpUxW0shIt1Mq_4b-fYWiGJYPXl7AJe5zUk/edit?usp=sharing ) with all the GA events I found in our codebase, along with the GTM equivalent events identified by Daniel Miranda (Thanks again for your great help!).

We were a bit surprised that not many events matched. However, considering Tyler's comment that some events are no longer tracked or not heavily used, it makes sense if some are missing.

We suggest the next step should be to get help from the Design Team. They are more familiar with the GTM tags and might identify GA events with different labels or descriptions in GTM, or confirm that the missing matches are no longer used.

Our goal is to finalize a reliable spreadsheet with the events to migrate, to assist whoever will work on this in the future, whether from the dev or design team.

Please let me know your thoughts and feel free to propose any other path! Tyler Denton
