### ISSUE TITLE
Add new field (PrivacyText) to Signup snipper for A/B test

### ISSUE THREAD

**Issue by data-sync-user** [MozillaFoundation/foundation.mozilla.org#12169]
### Describe the feature request

We would like to be able to set up the confirmation text after a submission through our signup to be A/B tested. Per Mavis message on this regard, the text and localized text is being hardcoded, but if we would like to allow for A/B Testing, we would need to add a new field to the Signup snippet on Wagtail and have the page render this text instead of the currently hardcoded one.

From Mavis:

> Add a new field privacy_text to [Signup](https://github.com/MozillaFoundation/foundation.mozilla.org/blob/main/network-api/networkapi/wagtailpages/pagemodels/campaigns.py#L127-L154) model and update the current [hardcoded privacy text](https://github.com/MozillaFoundation/foundation.mozilla.org/blob/main/source/js/components/newsletter-signup/organisms/default-layout-signup.jsx#L268-L270) with new privacy_text value (similar to how we render “header” and “description”). This will allow us to have the same campaign page linked to two Signup snippets (one original and one with the new privacy text we wanna test).

### Screenshot/Mockups

NA

### Additional Context

NA

┆Issue is synchronized with this [Jira Story](https://mozilla-hub.atlassian.net/browse/TP1-394)

**Comment by mmmavis** [comment]
Hello @TheoChevalier , I'd like to get your advice on this. Do you see any issues with this approach?

/cc @robdivincenzo

**Comment by TheoChevalier** [comment]
Hey @mmmavis , I’m not sure how the A/B testing feature works with localized pages/snippets, but I don’t see any issue in having one version hardcoded and another in a localized CMS field

**Comment by mmmavis** [comment]
Hey @TheoChevalier , for this A/B testing, it's basically on the CMS we pick the campaign page we wanna test, on its edit interface there's an option to enable A/B testing which we can then select a variant Signup snippet we wanna test against with.

Once we have a new field PrivacyText on Signup Snippet, we will use whatever privacy text staff set in the CMS instead of the current hardcoded strings in the codebase

For example,
- Snippet 1 ("normal" version): We enter our standard privacy text in the to-be-created PrivacyText field
- Snippet 2 (used as variant for A/B test): We have a different privacy text entered for the PrivacyText field

The campaign page will first need to be published with Snippet 1 as it's email signup component. Then we can set up A/B test with Snippet 2 as its variant. 

I do have one question regarding how we deal with all existing Signup snippets though - do we need to run migrations (or any other steps) to make sure they have default privacy text set in the CMS (along with the translations)?

**Comment by robdivincenzo** [comment]
> I do have one question regarding how we deal with all existing Signup snippets though - do we need to run migrations (or any other steps) to make sure they have default privacy text set in the CMS (along with the translations)?

Hey @mmmavis and @TheoChevalier, quick thoughts regarding the default text. I wonder if we should take the approach that this new PrivacyText field is an optional field that, when set, overrides the existing default privacy text. This would enable editors to customize the privacy text when desired. And when not desired, it would fallback to the existing hardcoded default that is backwards compatible and consistent across the site.

**Comment by mmmavis** [comment]
Hey @robdivincenzo sound good to me! I know eventually we would want to move away from having hardcoded strings in the codebase. But I like your suggestion for this ticket as it requires less dev work, has lower risk of messing existing snippets' privacy text, and less intimidating for staff to create a new signup snippet. In the help text of the new text, it would be helpful that we add a note about a standard/default privacy text will be used as fallback if the field is left blank.

**Comment by data-sync-user** [comment]
➤ Simon Acosta Torres commented:

Mavis Ou Whenever you have some time, could you please share on the ticket the comment that you initially shared? Thanks!

**Comment by data-sync-user** [comment]
➤ Mavis Ou commented:

I’ve updated the ticket description and also tagged Theo on GitHub to make sure we don’t run into localization issues.
