### ISSUE TITLE
`AppInstallPage` banner image appearing blurry

### ISSUE THREAD

**Issue by danielfmiranda** [MozillaFoundation/foundation.mozilla.org#12219]
┆Issue is synchronized with this [Jira Story](https://mozilla-hub.atlassian.net/browse/TP1-532)

**Comment by data-sync-user** [comment]
➤ Jhonatan Lopes commented:

We have a tailwind variant to check retina displays (https://github.com/MozillaFoundation/foundation.mozilla.org/blob/0fbae427f542a41d8e5419152c8f3c7883d98fb3/tailwind.config.js#L56 ( https://github.com/MozillaFoundation/foundation.mozilla.org/blob/0fbae427f542a41d8e5419152c8f3c7883d98fb3/tailwind.config.js#L56|smart-link ) )  and it was used on Mozfest: https://github.com/MozillaFoundation/foundation.mozilla.org/blob/0fbae427f542a41d8e5419152c8f3c7883d98fb3/network-api/networkapi/mozfest/templates/fragments/blocks/newsletter_signup_with_background_block.html#L42-L44 ( https://github.com/MozillaFoundation/foundation.mozilla.org/blob/0fbae427f542a41d8e5419152c8f3c7883d98fb3/network-api/networkapi/mozfest/templates/fragments/blocks/newsletter_signup_with_background_block.html#L42-L44|smart-link )

**Comment by danielfmiranda** [comment]
We identified that the root cause of the blurry image on the AppInstallPage Banner was due to the original image having a resolution below 2800px in width. The <picture> element in responsive_screen_wide_image.html is configured to request specific image resolutions based on the viewport size. For large retina screens, it specifically requests an image width of 2800px.

If the available image is less than 2800px wide, it must be stretched to meet this 2800px resolution requirement. This stretching results in a loss of sharpness.

We can now close this ticket as resolved 👍

**Comment by data-sync-user** [comment]
➤ Daniel Miranda commented:

We identified that the root cause of the blurry image on the AppInstallPage Banner was due to the original image having a resolution below 2800px in width. The <picture> element in responsive_screen_wide_image.html is configured to request specific image resolutions based on the viewport size. For large retina screens, it specifically requests an image width of 2800px.

If the available image is less than 2800px wide, it must be stretched to meet this 2800px resolution requirement. This stretching results in a loss of sharpness.

We can now close this ticket as resolved 👍
