### ISSUE TITLE
Adopt MultipleChooserPanel

### ISSUE THREAD

**Issue by data-sync-user** [MozillaFoundation/foundation.mozilla.org#12421]
There are a high number of InlinePanel uses across the site where each item only has one field (a Page, or author Profile) – [MultipleChooserPanel](https://docs.wagtail.org/en/stable/reference/pages/panels.html#multiplechooserpanel) would greatly simplify the experience.

┆Issue is synchronized with this [Jira Story](https://mozilla-hub.atlassian.net/browse/TP1-745)

**Comment by AdalbertoMoz** [comment]
I have a question related to this issue. To me, it seems that the `MultipleChooserPanel` is still somewhat "buggy," and it might be better to wait before merging PR #12514. Let me explain why:

When I first experimented with the `MultipleChooserPanel`, I migrated 2 `InlinePanels` to this new panel type, and it worked well. However, after migrating 39 `InlinePanels` to `MultipleChooserPanel` (across approximately 19 files), I noticed two unusual behaviors and found related issues on GitHub:

- **The search box breaks the checkbox for selection.** This is particularly problematic because some `InlinePanels` have many options, such as Blog Pages. when you use the search box, the `MultipleChooserPanel` displays search results, but you can't select them. This issue is [documented here](https://github.com/wagtail/wagtail/issues/11955), and there is a PR that might fix it.

- **The `MultipleChooserPanel` doesn't remember selected items while navigating through pages.** For example, if you select three items on the first page, navigate to another page and select one, then go to another page and select two more, only the items from the last page (the two items) are saved. This issue is also [documented here](https://github.com/wagtail/wagtail/issues/10754), with a potential fix in another PR.

(For a very detailed explanation of the issues, please go to the mentioned links)

These issues emerged within just 2-3 hours of testing. In my opinion, migrating from `InlinePanel` to `MultipleChooserPanel` seems risky. **The goal of this change is to simplify the user experience, but with these bugs, it might achieve the opposite effect.**

My recommendation is to mark this as "temporarily blocked," keep the changes I made in my PR for reference (in case they can be used later without modifications), and revisit this migration when the `MultipleChooserPanel` is more stable.

However, this is just my suggestion. Since I'm not fully aware of how real users and stakeholders use the Wagtail Page, it might be worth explaining these changes to them to see if they are willing to tolerate these issues temporarily. If not, it might be better to wait until these bugs are resolved.

@mtdenton @simont-cr

**Comment by mtdenton** [comment]
Agreed, let's not move forward with this for risk of breaking what we already have. Adding blocked label. Thanks for the thorough write-up @AdalbertoMoz

**Comment by data-sync-user** [comment]
➤ Kevin Duong commented:

Check if we can do this on Wagtail Ver 6.4
