### ISSUE TITLE
remove wagtail-modeltranslation inheritance

### ISSUE THREAD

**Issue by Pomax** [MozillaFoundation/foundation.mozilla.org#7891]
We have some code with `content_panels = Page.content_panels  # Needed for wagtail-modeltranslation to work` and we should verify whether we still need that (I suspect we do =D) or whether we can remove this everywhere now that we're using wagtail-localize

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/TP1-252)

**Comment by tbrlpld** [comment]
@Pomax I could use some clarification on what is necessary here and why we would want to remove it. 

Is this talking about page models? If so, using `content_panels = Page.content_panel + [...other panel types]` is used to extend the default list of content panels (I think this only really contains the `FieldPanel` for `title`) with the ones specific this the given page model. This is a fairly common practice not only used for translation. (E.g. see [this section in the Wagtail tutorial](https://docs.wagtail.org/en/stable/getting_started/tutorial.html#blog-index-and-posts)).

**Comment by mtdenton** [comment]
Timebox to 1 hour

**Comment by data-sync-user** [comment]
➤ diego commented:

Hi Simon Acosta Torres

Reviewing the description of this ticket and also the thread of the issue on github, I see that there’s a confusion or a lack of context regarding the request or consideration of content_panels removal. Because as Tibor @tbrlpld correctly higlights, content_panels are used to extend the model and also these editor panels defined how the filds will be arranged in the page editor interface. So this removal is not necessary.

I also add the link to Wagtail documentation where this is specified:

https://docs.wagtail.org/en/stable/topics/pages.html#editor-panels ( https://docs.wagtail.org/en/stable/topics/pages.html#editor-panels|smart-link )
