### ISSUE TITLE
Editing petition snippets from a campaign page links to the wrong form

### ISSUE THREAD

**Issue by TheoChevalier** [MozillaFoundation/foundation.mozilla.org#8253]
STR:
1- Edit a petition page, e.g. https://foundation.mozilla.org/cms/pages/16784/edit/#tab-content
![Screenshot 2022-02-15 at 15-12-22 Wagtail - Editing Campaign page (en) Tell Tinder It’s time for meaningful transparency into your pricing algorithms!](https://user-images.githubusercontent.com/1294206/154267291-565010d5-355e-4a36-a6fe-ff1c1b7ffcca.png)
2- Click “Edit this CTA” button, you land on the following page where many fields are missing:
![](https://user-images.githubusercontent.com/1294206/154268008-ee8eefa3-2c94-4845-bbf7-5af5757d915e.png)

It currently redirects to https://foundation.mozilla.org/cms/snippets/wagtailpages/cta/edit/224/ while it should redirect to https://foundation.mozilla.org/cms/snippets/wagtailpages/petition/edit/224/

Note the missing fields on the first link: campaign ID, ShareProgress, Thank You, etc.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/TP1-261)

**Comment by kristinashu** [comment]
@mtdenton I'm going to put this in the upcoming sprint (not to necessarily work on it but just so that people are aware of it as they do the other petition work).

**Comment by kristinashu** [comment]
This bug still exists

**Comment by mtdenton** [comment]
Hey @kristinashu! We're aware of the issue, however because of the way that `Petition`, `Signup`, and `CallPower` functionalities were implemented as "sub-snippets" of `CTA`, it would require either a significant amount of refactoring to the campaign page model/CTA models or some hacky fixes to change the link of that button.

@Gbaldassano if we want to bump up priority for this in the backlog we can (probably not a small task), but in the meantime, I feel like we need to expand our [petition documentation](https://foundation.mozilla.org/en/docs/how-do-i-wagtail/specific-pages/petitions/) and [snippet documentation](https://foundation.mozilla.org/en/docs/how-do-i-wagtail/specific-pages/snippets/) to be more clear about working around this issue. I think we should also edit our help text to further highlight this pitfall for folks who may not already be aware:

![helptext](https://github.com/MozillaFoundation/foundation.mozilla.org/assets/41487159/a1ffde82-978d-42c7-8af1-51e85998fefc)

**Comment by simont-cr** [comment]
@kristinashu Considering there's already a workaround in place and this has been for a while already, should we close or add it with a priority 3 instead?

**Comment by data-sync-user** [comment]
➤ Simon Acosta Torres commented:

Jhonatan Lopes Per Kristina last comment on GH, do you think this is a quick fix or we should close?
