### ISSUE TITLE
Add tag/topic validation for RecentBlogEntries block

### ISSUE THREAD

**Issue by danielfmiranda** [MozillaFoundation/foundation.mozilla.org#8832]
In **recent_blog_entries.py**, there is a TODO comment that says:

`    # TODO: add in validation so that if there are no tags or topic
          filled in we don't allow the page to be saved, with a wagtail
          error indication what's wrong.`

The goal of this ticket is to finish up that todo.

## Dev Tasks
* [x] Figure out if we still want to implement this filter requirement
* [x] If so, we can do validation using a new clean() method for the recent blog entry block, [here is a good existing example](https://github.com/mozilla/foundation.mozilla.org/blob/6dd856388050ca407385ee5d168f4f5c40a105b2/network-api/networkapi/wagtailpages/pagemodels/research_hub/detail_page.py#L53)

## Acceptance Criteria
If we decide to move forward with this work, acceptance criteria is as follows:

* [x] When a user uses a recent blog entries block, they must select either a tag or a category as a filter. If both or neither are selected, it will raise an error.
* [x]  Return an error letting the user know they need to select only one filter (either a tag or a category) or an error if no filter is selected.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/TP1-290)

**Comment by danielfmiranda** [comment]
Hi @simont-cr I do think that this is something that would be worth adding and not too much work. Going to add the P3 label

**Comment by AdalbertoMoz** [comment]
Hey @danielfmiranda, I have a question related to this ticket:

In the current code (link below), the query parameter controls what will be displayed. It appears that Topic has a higher priority than Tag, meaning that if both are selected, the Topic will be used instead of the Tag.

I found this comment inside the code:

https://github.com/MozillaFoundation/foundation.mozilla.org/blob/c9853c1dc98e0b3daf6a032499654e078f23a43c/network-api/networkapi/wagtailpages/pagemodels/customblocks/recent_blog_entries.py#L64-L69

After reading it, I think it would be a good idea to extend the task requirements to include the following validations:
- A Tag or a Topic must be selected; otherwise, raise an error.
- If both Tag and Topic are selected, raise an error as well.

In my opinion, having these two validations will make things clearer and more understandable, ensuring we know exactly what is used for filtering. However, I'm concerned that this new validation might break or block some existing pages when trying to edit them.

What do you think?

**Comment by danielfmiranda** [comment]
Hi @AdalbertoMoz!

Thanks for bringing this up, I agree that your suggested solution would be best, and after looking at the codebase I do not believe that implementing that validation would break anything 👍
