### ISSUE TITLE
[RH] Scrollable indicator

### ISSUE THREAD

**Issue by tbrlpld** [MozillaFoundation/foundation.mozilla.org#8855]
# Description
With the sticky "apply filter" button in the filter section of the research hub library page it can be hard to identify that I should be scrolling to see more filter options. On desktop you might when you scroll through the results. On mobile the filter options are displayed in a modal and not next to the results, so that mechanism does not exist.

**Desktop**
![](https://user-images.githubusercontent.com/24797493/171727746-f6159a0e-bfd1-4838-92ed-8f2ed26683ee.png)

**Mobile**
![](https://user-images.githubusercontent.com/24797493/171727765-e48ffd72-5b9f-40c4-abb0-b54cd07f4bf3.png)

I think it could be useful to have something like little arrow to indicate that I should be scrolling down. 

# Acceptance criteria
* [ ] We have a design proposal on how the need to scroll to discover more could be indicated.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/TP1-294)

**Comment by tbrlpld** [comment]
cc @kristinashu @beccaklam

**Comment by kristinashu** [comment]
On mobile, [our petition pages](https://foundation.mozilla.org/en/campaigns/facebook-update/) have a sticky button and we've used a shadow to hint that it is over top of other content. 

The shadow might work for the research hub but we would need to mock it up to see how it looks on desktop and with the grey background. Is this something Nick could do since he designed these pages? cc @bheasman 

<img width="376" alt="image" src="https://user-images.githubusercontent.com/1068783/174916172-e0b18871-afc5-46c5-a3c2-bba0ab8b1b74.png">

**Comment by bheasman** [comment]
Sorry, this one slipped through! Agree this definitely feels like something worth looking at. I'll have a chat with Nick

**Comment by nicklee** [comment]
Hi @kristinashu, I've just added a quick mockup to Figma which is also attached.

This illustrates how this component would work on desktop, notice the button has text transform uppercase on in your example, but our button is sentance case, if we want to be fully consistent we may want to update this on the research hub?

![Research-listing-fixed-button](https://user-images.githubusercontent.com/298766/180729638-7d2567f5-c792-4e78-b664-35f4a09073ff.png)

**Comment by kristinashu** [comment]
Thanks Nick, this looks good! No need for the text to be uppercase - I don't think it needs to be that prominent of a CTA.
