### ISSUE TITLE
Implement auto redirects package

### ISSUE THREAD

**Issue by bheasman** [MozillaFoundation/foundation.mozilla.org#9032]
### Describe the feature request
In order to easily enable editors to create the new Research Hub section of the website and move content, it'd be good to implement the auto-redirects package so that editors don't have to manually create redirects as part of the process.

https://github.com/themotleyfool/wagtail-automatic-redirects

### Acceptance Criteria

- [ ] As an editor, when I move a page within the CMS, I want a redirect to be created automatically so that I don't have to do this manually

**Comment by kristinashu** [comment]
I believe we have this feature now that we've updated to the new version of Wagtail and figured out our issues https://github.com/MozillaFoundation/foundation.mozilla.org/issues/9961

@jhonatan-lopes @mtdenton can you please confirm?

Please also confirm that this won't help for something like the Playbook? We want to redirect the old playbook https://foundation.mozilla.org/what-we-fund/awards/teaching-responsible-computing-playbook/ to the new one at  https://foundation.mozilla.org/responsible-computing-challenge-playbook/ 

The stakeholder is ok with all the subpages like https://foundation.mozilla.org/what-we-fund/awards/teaching-responsible-computing-playbook/authors-and-contributors/ to be redirected to the landing page https://foundation.mozilla.org/responsible-computing-challenge-playbook/. Is there an easier way to do this instead of having to do a redirect using https://foundation.mozilla.org/cms/redirects/ for every single sub page?

**Comment by jhonatan-lopes** [comment]
Hey @kristinashu, we have automatic redirect creation since version 2.16 (see https://docs.wagtail.org/en/v4.1.9/reference/contrib/redirects.html#automatic-redirect-creation). However, this is only when the slug for a page gets changed, for instance, if the RCC playbook changed the slug from "responsible-computing-challenge-playbook" to "rcc-playbook", Wagtail would automatically redirect the old URL to the new URL.

The second type of redirect (that your question pertains) is how to redirect a page (or URL) to another page where there is no relationship between them. This has to be managed through the ["redirects" interface](https://guide.wagtail.org/en-latest/how-to-guides/manage-redirects/) on "settings" at the CMS. You can upload a .csv file with multiple redirects at once to make the process easier.

**Comment by jhonatan-lopes** [comment]
Closing as this feature has been part of Wagtail core since version 2.16
