### ISSUE TITLE
Data Futures Lab - Default dropdown option showing as "undefined"

### ISSUE THREAD

**Issue by mtdenton** [MozillaFoundation/foundation.mozilla.org#9478]
### Describe the bug
https://foundation.mozilla.org/en/data-futures-lab/grantmaking/2023-prototype-fund/

When this page is viewed on mobile, the default dropdown option is "undefined".

### To Reproduce
1. Go to [ '...'](https://foundation.mozilla.org/en/data-futures-lab/grantmaking/2023-prototype-fund/)
2. Notice "undefined" in the first dropdown. Navigate to another option in the dropdown
3. See that "undefined" disappears in the dropdown options and the page can no longer be accessed.

### Expected behavior
From a DFL stakeholder:

"This is a new page that doesn't need to be accessible from the menu (and it is not an issue on large screens). If the dropdown needs to have something written there, it can be "Apply" - otherwise leaving blank would be fine."

### Screenshots
![dflsnip](https://user-images.githubusercontent.com/41487159/194935647-6349f3af-0203-45ef-8def-f8c30a944745.JPG)

### Additional context
There's a larger discussion that needs to be had about this view and its user friendliness, but that's for another day.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/TP1-302)

**Comment by mmmavis** [comment]
It says "Navigate to..." for me now. I think this is fixed. Closing.

**Comment by mmmavis** [comment]
Ah nvm, re-opening as I think the behaviour doesn't match what stakeholders' suggestion (mentioned in ticket description)

**Comment by mmmavis** [comment]
@kristinashu I'm unable to trace back to the stakeholder that had this request as the ticket was filed in 2022. Last year we have fixed the `undefined` text to `Navigate to...`. This is the universal default text for any page that is not listed in the dropdown. I'm tempted to mark this ticket as done. Could I get your thoughts on this? It would be pretty hacky if we want to set a special case `Apply" - otherwise leaving blank would be fine.` just for this DFL page. Thanks!

**Comment by kristinashu** [comment]
I'm going to close this! "Navigate to" is totally fine, as long as it doesn't say "undefined". The stakeholder was just giving some suggestions.
