### ISSUE TITLE
[PNI] Related article links are hardcoded to the English locale

### ISSUE THREAD

**Issue by TheoChevalier** [MozillaFoundation/foundation.mozilla.org#9551]
Related articles listed at the top of category pages are always linking to the English locale instead of the current locale.

Example, articles should link to the /fr/ versions here:
https://foundation-pni-2022.herokuapp.com/fr/privacynotincluded/categories/mental-health-apps/

![](https://user-images.githubusercontent.com/1294206/197767917-e57c1aa6-c2b8-4223-9317-9a4a09356de1.png)

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/TP1-304)

**Comment by mtdenton** [comment]
Thanks @TheoChevalier, prioritizing this for triage.

**Comment by danielfmiranda** [comment]
Hi @TheoChevalier! 

After trying to test this, I found that I am having a hard time replicating this. 

I was wondering if you could please leave some steps on how to get the English versions of the related article pages to show on the French page?

Whenever I try, nothing appears for the French page at all, even after sycing the translations of the Product Category after making any changes, as well as syncing translations of the "Privacy not included" home page.

I am feeling like this might be another instance of "need to update a `translatablefield` to a `synchronizedfield`" but since this needs more discussion/investigation, I will move this ticket to "in progress" and dive deeper next sprint.

**Comment by TheoChevalier** [comment]
Hey @danielfmiranda I’ve finally found some time to have a closer look, and unfortunately, like you, I didn’t manage to add articles to the category page. I’m not sure why it worked on staging, maybe it was the initial migration?

**Comment by cdanfon** [comment]
@tbrlpld please groom

**Comment by tbrlpld** [comment]
I am running into another issue. There are no related articles showing on the pages for the translated category:

1. Create related articles on a category, e.g.: https://foundation.mofostaging.net/cms/snippets/wagtailpages/buyersguideproductcategory/edit/3/ 
2. Directly navigate to that categories pages: https://foundation.mofostaging.net/en/privacynotincluded/categories/entertainment/. See the related links. Attention: the page needs to be loaded directly (or refreshed). When navigating to the PNI homepage (or another category page) and using the category navigation, the related articles won't show.
3. Synchronize translations of the category. 
4. Visit the page of the translation of the category: https://foundation.mofostaging.net/fr/privacynotincluded/categories/entertainment/. See that no links show up.

**Comment by tbrlpld** [comment]
@TheoChevalier @danielfmiranda I this the issue you had as well?

**Comment by danielfmiranda** [comment]
Hi @tbrlpld confirming that this is the same issue I was experiencing as well
