### ISSUE TITLE
SPIKE - Move "articles" out of product reviews in the CMS so it's easier to find

### ISSUE THREAD

**Issue by beccaklam** [MozillaFoundation/foundation.mozilla.org#9611]
## Context: 

Currently it's hard to find where to add article pages in PNI's CMS because the parent folder "Articles" is hidden within product reviews (see image below). Can we take it out and create more separation so that it's easier to find?
![Screen Shot 2022-11-02 at 3.28.41 PM.png](https://images.zenhubusercontent.com/57acd65ce40e5714b16d4215/825cc1eb-3cd3-49fb-b3f5-799b3d1041b5)

## Description:

This ticket is to create a 'product review' _index page_ that is parent to all the review pages in PNI and to create an 'article' _index page_ that is parent to all articles under the PNI page.

## Acceptance Criteria: 

- [ ] 'Articles' is an index page under PNI in the CMS
- [ ] 'Product reviews' is an index page under PNI in the CMS

**Comment by tbrlpld** [comment]
Turns out this is not changed in newer versions of Wagtail yet (I though a change was coming that shows pages with sub-pages first in the tree view). 

@beccaklam you can use the "sort order" view to manually order the pages: 
<img width="300" alt="Screen Shot 2022-11-28 at 13 10 22" src="https://user-images.githubusercontent.com/24797493/204382210-ac22ef0f-9cb6-4055-a6da-b1f11cdad823.png">


This manual sort order is used by default in the side panel navigation: 
<img width="300" alt="image" src="https://user-images.githubusercontent.com/24797493/204382122-af0f8af8-8159-4352-bcb8-2a25c5a2ddc4.png">

**Comment by tbrlpld** [comment]
@beccaklam I do a agree, this is a bit messy to find the articles. 

I would think the editorial content index should stay below the PNI homepage though, because that makes sense from the navigation and information architecture. 

I would propose to rather create a product review index or catalog page that is parent to all the review pages. This is not really a page we have at the moment. We are currently mixing the catalog/review index with the homepage. Maybe we should make that separation also a bit clearer. 

This is somewhat related to the conversions around showing less reviews on the homepage and rather link to the category/catalog page to see all of them.

**Comment by beccaklam** [comment]
> @beccaklam I do a agree, this is a bit messy to find the articles.
> 
> I would think the editorial content index should stay below the PNI homepage though, because that makes sense from the navigation and information architecture.
> 
> I would propose to rather create a product review index or catalog page that is parent to all the review pages. This is not really a page we have at the moment. We are currently mixing the catalog/review index with the homepage. Maybe we should make that separation also a bit clearer.
> 
> This is somewhat related to the conversions around showing less reviews on the homepage and rather link to the category/catalog page to see all of them.

This approach sounds great to me! cc: @kristinashu Do you have any input?

**Comment by kristinashu** [comment]
To clarify, you mean that if staff go to the CMS and click on PNI then they will see a "folder" for `product reviews` and another one for `articles` which they can then click into? If so then that sounds good. We hope to one day also have the about pages in the CMS so that could eventually be another folder at that level.

**Comment by tbrlpld** [comment]
@kristinashu Yes, that is exactly it. 

And yea, we could absolutely have the about pages in another "folder". 

I typically use the term "index pages" for these "folders", because the index pages do usually have a URL and some content themselves (even if just links (e.g. as cards) to the child pages). "Folders" in the sense they exist on the operating system don't exist in the Wagtail page structure.

**Comment by kristinashu** [comment]
Can this please be groomed so it can get into the upcoming sprint?

**Comment by cdanfon** [comment]
Hey @tbrlpld @kristinashu I've added some detail to the ticket description, can you please check if it looks good to you and tweak if needed?

**Comment by kristinashu** [comment]
They sound right to me, thank you!

**Comment by tbrlpld** [comment]
I'd like to raise that this is going to be quite a bit of work, because a lot of logic needs to be changed for this to happen. 

Folders in the tree view are not really "folders" on a computer's operating system. Each "folder" is a page in itself that has a level in the URL structure. 

I am not saying this is impossible, it's just bigger than "make a folder". Just wanted to raise awareness of this.

**Comment by kristinashu** [comment]
Come on Tibor, just right click and select New Folder lol!

Although I am realizing now that Articles is actually already in a folder under PNI (so I believe that AC isn't actually needed) so this is more about creating a Product Reviews folder and moving the reviews into that folder.

@tbrlpld should adding some dev todos to this ticket be part of the grooming? Would you please be able to do that?

**Comment by tbrlpld** [comment]
I've added this to my list. Hope to get to this tomorrow 👍

**Comment by kristinashu** [comment]
@mtdenton @cdanfon we're planning to have brown bag on Feb 27 to onboard staff on how to use the new PNI CMS features and it would make things much easier if this were live before then!

**Comment by cdanfon** [comment]
Hey @kristinashu, this ticket didn't make the cut into the sprint. Our next planning session is on the 20th (possibly 21st due to US holiday) and the next scheduled deployment that could include this feature would be on the 28th.

However, I can check with @tbrlpld later today about how his sprint is looking and see if it can be squeezed in. @mtdenton shout if any issues!

**Comment by cdanfon** [comment]
Timebox to 3/4 hours

GOAL: break down into smaller tasks

**Comment by tbrlpld** [comment]
@beccaklam @kristinashu Adding the product index page will also add a level in the URL. That means products that used to be accessible at `privacynotincluded/amazfit-powerbuds-pro/` will then be available at `privacynotincluded/products/amazfit-powerbuds-pro/`. Actually, from the code it looks like there used to be this level in the URL before PNI was converted to Wagtail pages. Based on the logs, these original URLs still seem to be used quite frequently. Currently, we are redirecting from `privacynotincluded/products/amazfit-powerbuds-pro/` to `privacynotincluded/amazfit-powerbuds-pro/`.

Is "products" a good name for the index page? Or would you call it "reviews"? Or "product reviews"? 

The level in the URL would also be a new page that could be surfaced. E.g. what happens when someone where to visit `privacynotincluded/products/`? Should there be a new kind of page rendered here? Should we just redirect to the homepage?

**Comment by tbrlpld** [comment]
Current state of the work: 

- [x]  Index page exists
- [x]  Product pages can live on the index page
- [x]  Product pages can not be created at the home page
- [x]  Factories are updated → new fake data has the review page level.
- [x]  Functional tests / Percy tests are updated
- [x]  Search works
- [x]  Category pages work
- [x]  `product_view` route remains working… but will probably not be hit… → Nope, this does not work. This leads to a redirect loop if the page is called “products”.  Well, easy fix for now is to call the page something different than “products”. The ticket seems to mention “product reviews” as the desired title. That is also more accurate. Since I will be creating this in s data migration, I think we should be fine. Seems unlikely that this would be the first thing an editor changes.
- [x]  Child page pages are served from below the index page. This means the index slug is in the URL.
- [ ]  Index page itself does not render anything, it redirects to home page (parent)
- [ ]  Data migration moves all products from the home page to an index page, for all locales. Pages to have a `move` method. This should set up the redirects automatically.
- [ ]  Redirects redirect from the old product locations to the new one.
- [ ]  Redirects need to be working

**Comment by tbrlpld** [comment]
I was able to already get the some work started, because it was more straight forward than anticipated #10191. 

The open tasks might take another 2hrs. 

Before we can merge this though, we want to be sure that redirects are working properly.

**Comment by tbrlpld** [comment]
Hit a couple of snags trying to get a script in place to move the page from one location to the other. 

* Moving pages in migrations is not great, because you don't have access to tree manipulation manager methods like `add_child`. 
* Opted to go with a script. 
* Tried the tree node / page method `move`. Looked like they pages were moved, but they would not actually move. Very confusing. 
* Found `wagtail.actions.move_page`. Got this working after a bit. 
* Moving pages in default locale with script works (have a backward script too). 
* Need to extend the script to work in all locales.

**Comment by kristinashu** [comment]
Sorry I haven't had a chance to look at this more yet but changing the url for every product page is not wanted. A requirement of the editorial work was that it didn't change the product page urls. Can we please discuss before moving forward?

**Comment by tbrlpld** [comment]
@kristinashu The move of the page does set up redirects too. Of course, we need redirects to be working in that case. 

Making this work with the level in the admin but not the URL is going to add extra work and going the be confusing in the future. 

Can I ask what the rational behind not changing the product URLs is?

**Comment by kristinashu** [comment]
Thanks Tibor. Not changing the product urls was the one and only request from the marketing team when we asked for their input on the editorial work so it is important to me that they are looped in on this before moving ahead with it. But I'm sure your reassurance about redirects will help as I'm pretty sure broken links is their main concern.

I also just want to extra extra make sure that there is really no simpler way to do this? The issue is that it is hard to navigate to "Articles" when there are dozens of products above it. Is there any other way to have "Articles" more discoverable in the CMS?

**Comment by tbrlpld** [comment]
Thanks for the explanation @kristinashu. 

This is the simplest way of doing it, everything else would be some strange custom solution. As I mentioned, there is no such thing as a "folder" in Wagtail. What you navigate in the admin is the page tree. That page tree is the same structure as the one the users navigate when visiting the site. Thus, creating a level in the admin to group the products, will also group the products for the visitors and create a new section in the URL.

Now, we can create a workaround. Actually, the code already contains something similar. It seems like in the past, before Wagtail pages were used for PNI the products were grouped under a `/products/` section in the URL. Currently, if someone visits a product URL with that prefix, e.g. https://foundation.mozilla.org/en/privacynotincluded/products/threema/ it redirects them to the real URL of the page, https://foundation.mozilla.org/en/privacynotincluded/threema/. I checked the logs and a surprising amount of requests are still going to pages with the `/products/` section in the URL.

What we would need to add to this is that https://foundation.mozilla.org/en/privacynotincluded/threema/ should not really look for a page at this location in the backend. Instead, we would serve/show a page that would normally live at https://foundation.mozilla.org/en/privacynotincluded/product-reviews/threema/. 
If someone were to visit the real URL of the page (https://foundation.mozilla.org/en/privacynotincluded/product-reviews/threema/) we would redirect them to the fake URL (https://foundation.mozilla.org/en/privacynotincluded/threema/) that is set up to show the original page. 

All a bit complicated and unusual. So the more simple way would be to just set up redirects from the current URLs (e.g. https://foundation.mozilla.org/en/privacynotincluded/threema/) to the new ones (https://foundation.mozilla.org/en/privacynotincluded/product-reviews/threema/). 

One question is also: what to do if someone visits https://foundation.mozilla.org/en/privacynotincluded/product-reviews/. Here we could just redirect to https://foundation.mozilla.org/en/privacynotincluded/ because we don't have anything else designed to show there at the moment. 

Ultimately, I would prefer this to show the "category" page filtered for "all reviews" (similar to https://foundation.mozilla.org/en/privacynotincluded/#product-review but without the hidden header, like you get on category pages https://foundation.mozilla.org/en/privacynotincluded/categories/best-of/)... all of this should be part of refactoring PNI though and does not need to be dealt with as part of this.

**Comment by kristinashu** [comment]
Thank you for putting so much thought into this and explaining everything!

Based on our conversation with Jen and Audrey during today's brown bag, they are ok with changing the urls! So we will go with https://foundation.mozilla.org/privacynotincluded/product-reviews/threema/

Redirecting https://foundation.mozilla.org/privacynotincluded/product-reviews/ to https://foundation.mozilla.org/privacynotincluded/ (at least for now) sounds fine to me.

The hack of just re-publishing the Article page so it appears at the top of this list in the CMS feels like an OK bandaid for now so although this work would be great to have done it doesn't feel as pressing as it did before.

**Comment by simont-cr** [comment]
Hi @kristinashu , do you feel we should still put some time for this as a P2 for this year or this can be closed as stale?
