### ISSUE TITLE
Implement a more conventional Docker setup

### ISSUE THREAD

**Issue by tbrlpld** [MozillaFoundation/foundation.mozilla.org#9690]
## Description

We are currently using Docker in a fairly unconventional way. I have tried to write out steps we should take and what end state we might want, but trying to formulate the acceptance criteria only uncovered more questions. 

I think we should therefore do a spike to investigate why our setup is the way it is and and what potential improvements could look like (and also make it look more like conventional Docker setups -- ones that have stuff defined in their Dockerfiles). 

Here are is my currently list of notes, thoughts and questions about out Docker setup: 

### Mounted dependencies

* We are mounting the host app director to the container (`.:/app`). 
* But then we also create a volume for the virtual environment and the node modules which lives in the app directory in the container (`dockerpythonvenv:/app/dockerpythonvenv/` and `node_modules:/app/node_modules/`). 
* All dependencies are installed into these directories by the invoke script. 
* This means we have a weird nesting of [bind mounts](https://docs.docker.com/storage/bind-mounts/) and [volumes](https://docs.docker.com/storage/volumes/). 
* Bind mounts live at the specified location on the host filesystem. 
* It seems like this setup would mean that the dependencies are stored twice on the host and that every lookup of the dependencies is going through this nesting and the two overlapping storage locations. 
* Volumes on the other hand live in a specific Docker-controlled directory on the host. 
* I wonder if this is part of the performance issues we are seeing. 
* I am assuming the point of storing the dependencies in the bind mounts is to make them discoverable by editors on the host.
* Bing mounts mount a file or directory from the host into the container. 
* This means the container content is overridden. 
* So when we keep overriding the container content with what's on the host then there is no point to build the dependencies into the image. 
* Are the executables from the environments (`dockerpythonvenv` and `node_modules`) even available on the host? Would it be better to use devcontainers or somehow define remote interpreters? -> Turns out that is already the [recommended way to connect VS Code to the docker environment](https://github.com/mozilla/foundation.mozilla.org/blob/main/docs/local_development.md#connecting-docker-to-your-code-editor) in the container. 
* It turns out the `dockerpythonvenv` and `node_modules` directories on the host are empty. So this is no help to editors for autocomplete. 
* So these directories just end up in the local repo directory because the repo is first mounted into the container (`.:/app`) and then the volumes are added on top of that... And somehow the files in the volumes are not visible on the host, but the directories are... 
* Why do we need these environment directories anyhow? Since the environment are already isolated into containers, we could install the dependencies globally in the container. 
* It is mentioned in our [docs](https://github.com/mozilla/foundation.mozilla.org/blob/main/docs/local_development.md#python) that the dependencies are stored on the filesystem but not explicitly why. Is it only to save a build after installing dependencies? 
* It looks like installing node dependencies globally is a weird thing to do if you want to use it in your code (rather than just running executables). This means we can not mount the whole root directory into the frontend container, because that would override the `node_modules` directory. So we might need to mount only the files and directories we need into the frontend container. 🤔 Is this why we ended up with this mount-volume nesting? Maybe: https://www.cloudbees.com/blog/using-docker-compose-for-nodejs-development... yea, the seems like this is more common than I expected and even necessary: https://stackoverflow.com/a/32785014 
* There still is a difference in that these sources I am finding are using just data volumes, not named volumes. Wonder if that makes any difference. 

### Assets build on start not image build

* We are running our build in the start command. 
* This means we are rebuilding all assets on every container start. 
* This is really slow. 
* Especially our CSS setup takes a long time to build. 
* This is particularly frustrating when reviewing a lot of code and switching branches a lot. 
* Build compiled assets into the image, only watch for changes in the running frontend container. 
* This should improve the start up time. 
* Are assets that are build into the image overridden when the local directory is mounted into the container? Probably. Maybe we need to also protect these build assets in a volume.

### Two Dockerfiles

* The frontend image is build from a different Dockerfile than the backend image.
* But, we do need the frontend assets available in the backend container, because the backend container is serving the files.
* We could use [multi-stage builds](https://docs.docker.com/build/building/multi-stage/). 
* We only need one Dockerfile for the node and python environment.
* Only install the node dependencies in the node container, build the assets and copy the assets to the backend container during build. 
* The [`target` definition](https://docs.docker.com/compose/compose-file/build/#target) in the compose file can select which stage a given container should run. One can run with what's build at the end of the node stage and watch new assets. The other container runs off the backend stage. The watched assets are copied from the frontend to the backend container via a shared mount (read write on the frontend, read on the backend)
* Using the build stages also allows us to copy the assets from the frontend image into the backend image so that they are immediately available when the backend container starts. I guess this is less important in our use case because we only as we currently only use the containers in development.

### Other

* We currently have `backend` and `watch-static-files`. `backend` and `frontend` would feel a bit more consistent. 
* `npm run start` wants to start the Docker stack. But, all the other `npm` commands are meant to run inside a started stack. This is confusing. `inv` on the other hand is meant to run outside the Docker stack, but it provides short hands for commands you would run locally to perform some action in the container. It would feel more consistent to have `inv start` start the Docker stack and use `npm run start` to as the start command for the watch process inside of the frontend container.
* Why is the `dockerpythonvenv` mounted into the frontend container? 
* Can we make use of the containers and the `invoke` commands that control the containers in CI? That would reduce some duplication of the commands and make sure we are really running the same checks locally and in CI.

### References

* https://github.com/nodejs/docker-node/blob/main/docs/BestPractices.md#global-npm-dependencies
* https://docs.npmjs.com/cli/v7/configuring-npm/folders
* https://stackoverflow.com/questions/36245831/accessing-node-modules-after-npm-install-inside-docker
* https://www.cloudbees.com/blog/using-docker-compose-for-nodejs-development
* https://stackoverflow.com/a/32785014

## Goals (Acceptance criteria)

- [ ] The `inv new-env` command builds the Docker containers.
- [ ] There is an `inv start` command to start the Docker stack. 
- [ ] The `inv catchup` command rebuilds the frontend and backend containers. 
- [ ] The database is not wiped during `inv catchup`.
- [ ] The database is wiped during `inv new-env`.
- [ ] There are no empty `dockerpythonenv` and `node_modules` directories in the project directory on the host? Maybe these need to exist (at least the `node_modules` directory might)...
- [ ] When starting the container stack the frontend assets are already build and immediately available (based on the state when the container was last build). **This is the most important goal**, I think.
- [ ] When the frontend container starts it runs a watch process to rebuild the frontend assets when the source files change. 
- [ ] There is only one `Dockerfile` that builds the frontend and backend container as different stages. 
- [ ] Even if we keep everything the same (which I don't think), it would be good to expand the documentation on our Docker setup.

**Comment by patjouk** [comment]
I found this randomly, and from the bottom of my heart: I'm so sorry you have inherited the task of untangling my badly overengineered mess 😭 I was a very excited junior when I started this, and it grew out of control real quick.

I'm not sure if anyone from the old engineering team is still around to tell you why we have this thing in the first place. Let me see what I can remember.

I think it all boils down to folks struggling with python virtualenv and me, who took the bad decision of starting to add tools to "hide the complexity" instead of organizing training. I also remember my manager telling me that devs were used to running django commands using `npm run X`, and that was when the whole invoke thing started.

I [started with pipenv](https://github.com/mozilla/foundation.mozilla.org/pull/1320), which, let's say it that way, had some pros and cons. A year later, [we switched to docker ](https://github.com/mozilla/foundation.mozilla.org/pull/3002) because why not. Saying "switch" also hides some of the trut: I remember maintaining both pipenv and docker invoke commands for a while... You will probably find PRs that claim to ["simplify" stuff](https://github.com/mozilla/foundation.mozilla.org/pull/3673), when they are, in fact, just adding more workarounds on top of other workarounds. And the worst part in all that: we were not even using docker in prod, just for local dev.

It was not all bad when it was working. I remember the designers being extremely happy to be able to run the website on their machines by just entering a command. We were also super excited to be able to run our python dev environment using the brand new pycharm or vscode docker integrations. But yeah, it grew out of control, and again, I'm very sorry.

I remember the dependency management being its own special mess. I'm pretty sure it's the main reason the docker setup is that way. Sadly, I can't remember the details of why we ended up with those weird volumes and why it was working. I remember we were able to use IntelliSense, so if this is not working anymore, you can probably rip all of it and start from scratch.

And that's the terrible story behind our terrible invoke and docker setup.

If you ever happen to be in Berlin, send me a message. I will pay you the beverage of your choice and tell you again, how sorry I am for this and the other messes you probably ran into 😄

**Comment by tbrlpld** [comment]
Thanks for the backstory on this @patjouk! This is going to be very helpful when I get a round to add my "simplification" PRs 😅

**Comment by tbrlpld** [comment]
Just came across this: https://github.com/nodejs/docker-node/blob/main/docs/BestPractices.md#global-npm-dependencies

So it looks like you can use global nom dependencies

**Comment by victoriachan** [comment]
Just an update: I've forked this to work on this ticket. Currently I have created a new multi-stage Dockerfile, and moving the tasks in `inv new-env` to the Dockerfile as suggested. Still WIP, so nothing to see yet.

**Comment by victoriachan** [comment]
I've created the multi stage Dockerfile, and tweaked things in the docker-compose.yml and tasks.py. I've moved the tasks like pip install etc. to the Dockerfile. Though it is roughly working, there is still more work to do. Such as adding `inv start`, watching frontend files, updating tasks.py and documentation.

Currently as it is still in very rough state, I am keeping this in my fork. https://github.com/victoriachan/foundation.mozilla.org/pull/1

**Comment by victoriachan** [comment]
FYI I've added `inv start` and frontend files are working now. I am continuing with the list of ACs and making sure existing inv tasks are still working. Still on working on my fork and quite rough.

**Comment by victoriachan** [comment]
This is nearly done. There are 2 remaining issues:

1. When running `inv isort-check` I got an error `fatal: detected dubious ownership in repository at '/app' issue`.
2. I need to check that the instructions for running Playright locally still applies: https://github.com/MozillaFoundation/foundation.mozilla.org/blob/main/README.md#integration-tests .

**Comment by victoriachan** [comment]
@nickmoreton This is ready for review. I have created a new PR on the Mozilla repo (not my fork): https://github.com/MozillaFoundation/foundation.mozilla.org/pull/10742

It's quite a big one. Let me know if you want me to walk you through it or explain anything.

**Comment by victoriachan** [comment]
FYI: I'm currently working on the code review feedback. There is just the issue with CSP on Wagtail admin page left.

**Comment by victoriachan** [comment]
When reviewing the PR, @nickmoreton noted out an issue with the Wagtail admin preview. It wasn't loading due to some CSP errors. I tested the original docker setup, and indeed it also has this issue, so it isn't introduced by my change.

s there already a ticket for this elsewhere? Can we split it up to a separate ticket so we can move on with this one?

**Comment by jhonatan-lopes** [comment]
The wagtail admin preview not working was there before, but it is actually intentional due to the CSP policy. It is fixed by each dev by changing the `CSP_FRAME_ANCESTORS` environment variable to `self`:

```
CSP_FRAME_ANCESTORS=" 'self' "
```

**Comment by victoriachan** [comment]
@cdanfon Sorry, I have just found a bug. While trying to install pattern library for the next ticket, I discovered that the `inv pip-compile-lock` (as instructed in README.md for installing new python packages), is not working as expected. I'm investigating this.

**Comment by cdanfon** [comment]
Thanks for flagging @victoriachan I've added you to the ticket and marked it as 'in progress'

**Comment by cdanfon** [comment]
@jhonatan-lopes is going to have a look at this to see if he can help Victoria

**Comment by victoriachan** [comment]
To clarify, it looks like there is an issue with running `pip-compile` to compile the requirements.in files to requirements.txt. 

**How to replicate:**

1. Edit requirements.txt to add a new package, e.g. `django-pattern-library`
2. Run `inv pip-compile-lock`
3. It looks like no errors, but the requirements.txt file is unchanged. What should happen: the requirements.txt file should be edited to include the new package.

**Comment by victoriachan** [comment]
I have fixed the issue with `pip-compile`. 

I am now looking at the issue with `load_fake_data` which @jhonatan-lopes encountered.

**Comment by victoriachan** [comment]
The `load_fake_data` issue turned out to only be specific to @jhonatan-lopes's machine.  So we can ignore it.

However sadly I have found an issue while running `inv isort` or `inv format-python` (which runs inv isort) if any of the mount points (e.g. tasks.py) needs correcting. You would get a `Device or resource busy` error.

This is the same issue we had with `pip-compile`  trying to replace requirements.txt, isort tries to replace the mounted file, but is unable to do so as you can't delete or replace a mount point. It wouldn't be a problem if the file were in a subdirectory, or if isort just writes to the file (like Black does).

`inv isort-check` has no problem though. But the feedback from it isn't really helpful for dev to use to correct it by hand.

**Comment by victoriachan** [comment]
I've fixed the issue with isort. Thanks to[ overwrite-in-place](https://pycqa.github.io/isort/docs/configuration/options.html#overwrite-in-place) option.

I've also tested and tweaked the npm commands, so it should work as expected now.

We can finally pass this to the team to test.
