### ISSUE TITLE
Move utility functions from `__init__.py` to `utils.py`

### ISSUE THREAD

**Issue by tbrlpld** [MozillaFoundation/foundation.mozilla.org#9844]
There are a couple of utility functions and overrides defined in https://github.com/mozilla/foundation.mozilla.org/blob/main/network-api/networkapi/wagtailpages/**init**.py

We should move these into a more appropriate location if possible. E.g. https://github.com/mozilla/foundation.mozilla.org/blob/main/network-api/networkapi/wagtailpages/utils.py

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/TP1-314)

**Comment by tbrlpld** [comment]
@TheoChevalier Are there any blockers against moving the functions to the `utils.py` module?

**Comment by TheoChevalier** [comment]
@tbrlpld I was under the assumption that part of the hack was to keep functions in this file, but as long as the hack still works and we can override Django’s functions, I don’t see why it would be an issue.

We will just want to check `/pt-BR/*` or `/fy-NL/*` URLs still work as expected

**Comment by tbrlpld** [comment]
Thanks for the info @TheoChevalier. I guess we could move only the function definition and leave the override in the `__init__.py` (as I am assuming this relies on override during app import).

**Comment by mtdenton** [comment]
Via SD work week, reinvestigate this and see if it's still necessary

**Comment by dlopezvsr** [comment]
This [PR ](https://github.com/MozillaFoundation/foundation.mozilla.org/pull/12717  )proposes a slightly different idea of the initial issue description due to some current limitations. Moving the override functions from the `__init__.py` file to `utils.py` causes some conflicts related to circular imports where wagtail complains. Also
https://code.djangoproject.com/ticket/31795#no1 resolution was negative with a wontfix response. Considering that, another file was created to avoid circular import conflicts (`override_utils.py`) where the functions were moved, and are imported from in the `init.py`
