### ISSUE TITLE
FRU | GA4 implementation

### ISSUE THREAD

**Issue by cdanfon** [MozillaFoundation/foundation.mozilla.org#9939]
Ticket to track the implementation of e-commerce tracking for Fundraise Up on https://foundation.mozilla.org/en/ being carried out by Torchbox

PROD: https://foundation.mozilla.org/en/
STAGING: https://foundation.mofostaging.net/en/

**Comment by mtdenton** [comment]
What's the plan here? There's a lot of things that we'll likely want to track through the FRU dashboard since that functionality is available

**Comment by phoang0** [comment]
Hi Tyler, just jumping in here as I'm the analyst who is looking at setting up the e-commerce tracking on https://foundation.mozilla.org/en/ 

Before we can send any datalayer script, we noticed that there are a few issues with the donation funnel which could impact this work.

- The employee contribution prompt here takes the user straight to the confirmation page regardless whether the user clicks 'continue' or 'Skip to next step'. Are you able to confirm whether one of the CTAs is supposed to direct users elsewhere? 

![Screenshot 2023-01-11 at 14 55 33](https://user-images.githubusercontent.com/122810358/213415488-3fc0f818-4378-4249-82db-3cf87391753d.png)

- When a user makes a single donation, there is a CTA that encourages them to make a monthly donation. Both CTA take the user to the same confirmation page however it would seem that the 'Yes, I'll give monthly' CTA should actually take the user to the start of the donation funnel instead. 

![Screenshot 2023-01-11 at 14 56 15](https://user-images.githubusercontent.com/122810358/213415775-0e4c5563-ae35-41e9-a6e7-eae442208dd9.png)

![Screenshot 2023-01-11 at 14 58 41](https://user-images.githubusercontent.com/122810358/213415839-c0e02176-6bf5-4c74-ad3d-eab8efbca424.png)

Let me know if you have any questions.

**Comment by phoang0** [comment]
Hi @mtdenton and @kristinashu 

Following up on our call last week, we've looked at the existing e-commerce script and made some notes below.

- PII is being collected in the datalayer when the user reaches the payment funnel. This includes; email, names, employer name (if applicable) and an ‘ID’ although it is not clear what this ID relates too. To confirm, we’re not collecting this in GA however we would advise to remove this from the datalayer nonetheless to avoid any potential GDPR breaches.
- The current script can be used to track e-commerce data in GA4 but we would only be able to track the final purchase event rather than the entire payment funnel.
      - Note: to track the entire payment funnel, we would need too implement a datalayer script however this might not be possible with the donation platform. I believe Tyler is raising this  with the Fundraise Up team separately.
- The e-commerce events currently only tracks when the user makes a purchase or opens/closes the donation platform. Ideally, we would update these triggers to fire when the user; begins checkout, adds their payment info, and makes a purchase. Again, we would need to check with the Fundraise Up team on whether this is possible.

**Comment by simont-cr** [comment]
@kristinashu @abi-mofo Considering the parallel work that is happening regarding the Cookie Banner and how this might affect other metrics, is this a ticket that we would like to keep available or should we close and then reopen with updated information if we need to?
